# Copyright (C) 2001-2020, Python Software Foundation
# This file is distributed under the same license as the Python package.
# Maintained by the python-doc-es workteam.
# docs-es@python.org /
# https://mail.python.org/mailman3/lists/docs-es.python.org/
# Check https://github.com/python/python-docs-es/blob/3.8/TRANSLATORS to get
# the list of volunteers
#
msgid ""
msgstr ""
"Project-Id-Version: Python 3.8\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-10-25 19:47+0200\n"
"PO-Revision-Date: 2022-10-30 21:19-0300\n"
"Last-Translator: Marco Richetta <marcorichetta@gmail.com>\n"
"Language-Team: python-doc-es\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"Generated-By: Babel 2.10.3\n"
"X-Generator: Poedit 3.1.1\n"

#: ../Doc/library/exceptions.rst:4
msgid "Built-in Exceptions"
msgstr "Excepciones incorporadas"

#: ../Doc/library/exceptions.rst:10
msgid ""
"In Python, all exceptions must be instances of a class that derives from :"
"class:`BaseException`.  In a :keyword:`try` statement with an :keyword:"
"`except` clause that mentions a particular class, that clause also handles "
"any exception classes derived from that class (but not exception classes "
"from which *it* is derived).  Two exception classes that are not related via "
"subclassing are never equivalent, even if they have the same name."
msgstr ""
"En Python, todas las excepciones deben ser instancias de una clase que se "
"derive de :class:`BaseException`. En una instrucción :keyword:`try` con una "
"cláusula :keyword:`except` que menciona una clase determinada, esa cláusula "
"también controla las clases de excepción derivadas de esa clase (excepto las "
"clases de excepción de las que se deriva *it*). Dos clases de excepción que "
"no están relacionadas mediante subclases nunca son equivalentes, incluso si "
"tienen el mismo nombre."

#: ../Doc/library/exceptions.rst:19
msgid ""
"The built-in exceptions listed below can be generated by the interpreter or "
"built-in functions.  Except where mentioned, they have an \"associated "
"value\" indicating the detailed cause of the error.  This may be a string or "
"a tuple of several items of information (e.g., an error code and a string "
"explaining the code).  The associated value is usually passed as arguments "
"to the exception class's constructor."
msgstr ""
"Las excepciones predefinidas enumeradas a continuación pueden ser generadas "
"por el intérprete o funciones predefinidas. Excepto donde se mencione lo "
"contrario, tienen un *associated value* que indica la causa detallada del "
"error. Esto podría una cadena de caracteres o una tupla elementos con "
"grandes elementos de información (por ejemplo, un código de error y una "
"cadena que explica el código). El valor asociado generalmente se pasa como "
"argumentos al constructor de la clase de excepción."

#: ../Doc/library/exceptions.rst:26
msgid ""
"User code can raise built-in exceptions.  This can be used to test an "
"exception handler or to report an error condition \"just like\" the "
"situation in which the interpreter raises the same exception; but beware "
"that there is nothing to prevent user code from raising an inappropriate "
"error."
msgstr ""
"El código de usuario puede lanzar excepciones predefinidas. Esto puede ser "
"usado para probar un gestor de excepciones o para notificar una condición de "
"error \"igual\" a la situación en la cual el intérprete lance la misma "
"excepción; pero tenga en cuenta que no hay nada que impida que el código del "
"usuario produzca un error inapropiado."

#: ../Doc/library/exceptions.rst:31
msgid ""
"The built-in exception classes can be subclassed to define new exceptions; "
"programmers are encouraged to derive new exceptions from the :exc:"
"`Exception` class or one of its subclasses, and not from :exc:"
"`BaseException`.  More information on defining exceptions is available in "
"the Python Tutorial under :ref:`tut-userexceptions`."
msgstr ""
"Las clases de excepción predefinidas pueden ser usadas como subclases para "
"definir otras nuevas; se recomienda a los programadores que deriven nuevas "
"excepciones a partir de la clase :exc:`Exception` o de una de sus subclases, "
"y no de :exc:`BaseException`. Hay disponible más información sobre la "
"definición de excepciones en el Tutorial de Python en :ref:`tut-"
"userexceptions`."

#: ../Doc/library/exceptions.rst:39
msgid "Exception context"
msgstr "Contexto de una excepción"

#: ../Doc/library/exceptions.rst:41
msgid ""
"When raising a new exception while another exception is already being "
"handled, the new exception's :attr:`__context__` attribute is automatically "
"set to the handled exception.  An exception may be handled when an :keyword:"
"`except` or :keyword:`finally` clause, or a :keyword:`with` statement, is "
"used."
msgstr ""
"Al lanzar una nueva excepción mientras otra excepción está siendo manejada, "
"el atributo :attr:`__context__` de la nueva excepción es automáticamente "
"asignado a la excepción manejada.  Una excepción puede ser manejada cuando "
"se utiliza la cláusula :keyword:`except` o :keyword:`finally`, o con la "
"sentencia :keyword:`with`."

#: ../Doc/library/exceptions.rst:47
msgid ""
"This implicit exception context can be supplemented with an explicit cause "
"by using :keyword:`!from` with :keyword:`raise`::"
msgstr ""
"Este contexto de excepción implícita se puede complementar con una causa "
"explícita usando :keyword:`!from` con :keyword:`raise`::"

#: ../Doc/library/exceptions.rst:53
msgid ""
"The expression following :keyword:`from<raise>` must be an exception or "
"``None``. It will be set as :attr:`__cause__` on the raised exception. "
"Setting :attr:`__cause__` also implicitly sets the :attr:"
"`__suppress_context__` attribute to ``True``, so that using ``raise new_exc "
"from None`` effectively replaces the old exception with the new one for "
"display purposes (e.g. converting :exc:`KeyError` to :exc:`AttributeError`), "
"while leaving the old exception available in :attr:`__context__` for "
"introspection when debugging."
msgstr ""
"La expresión que sigue a :keyword:`from<raise>` debe ser una excepción o "
"``None``. Se establecerá como :attr:`__cause__` en la excepción generada. La "
"configuración de :attr:`__cause__` también establece implícitamente el "
"atributo :attr:`__suppress_context__` en ``True``, de modo que el uso de "
"``raise new_exc from None`` reemplaza efectivamente la excepción anterior "
"con la nueva para fines de visualización (por ejemplo, conversión de :exc:"
"`KeyError` a :exc:`AttributeError`), dejando la excepción anterior "
"disponible en :attr:`__context__` para introspección durante la depuración."

#: ../Doc/library/exceptions.rst:62
msgid ""
"The default traceback display code shows these chained exceptions in "
"addition to the traceback for the exception itself. An explicitly chained "
"exception in :attr:`__cause__` is always shown when present. An implicitly "
"chained exception in :attr:`__context__` is shown only if :attr:`__cause__` "
"is :const:`None` and :attr:`__suppress_context__` is false."
msgstr ""
"La visualización por defecto de la traza de error muestra estas excepciones "
"encadenadas además de la traza de la propia excepción. Siempre se muestra "
"una excepción encadenada explícitamente en :attr:`__cause__` cuando está "
"presente. Una excepción implícitamente encadenada en :attr:`__context__` "
"solo se muestra si :attr:`__cause__` es :const:`None` y :attr:"
"`__suppress_context__` es falso."

#: ../Doc/library/exceptions.rst:68
msgid ""
"In either case, the exception itself is always shown after any chained "
"exceptions so that the final line of the traceback always shows the last "
"exception that was raised."
msgstr ""
"En cualquier caso, la excepción en sí siempre se muestra después de "
"cualquier excepción encadenada para que la línea final del seguimiento "
"siempre muestre la última excepción que se generó."

#: ../Doc/library/exceptions.rst:74
msgid "Inheriting from built-in exceptions"
msgstr "Heredando de excepciones incorporadas"

#: ../Doc/library/exceptions.rst:76
msgid ""
"User code can create subclasses that inherit from an exception type. It's "
"recommended to only subclass one exception type at a time to avoid any "
"possible conflicts between how the bases handle the ``args`` attribute, as "
"well as due to possible memory layout incompatibilities."
msgstr ""
"El código del usuario puede crear subclases que heredan de una excepción. Se "
"recomienda heredar solo de una clase de tipo excepción a la vez para evitar "
"cualquier conflicto posible en el manejo del atributo ``args`` por parte de "
"las clases base, como también por posibles incompatibilidades en de la "
"memoria."

#: ../Doc/library/exceptions.rst:83
msgid ""
"Most built-in exceptions are implemented in C for efficiency, see: :source:"
"`Objects/exceptions.c`.  Some have custom memory layouts which makes it "
"impossible to create a subclass that inherits from multiple exception types. "
"The memory layout of a type is an implementation detail and might change "
"between Python versions, leading to new conflicts in the future.  Therefore, "
"it's recommended to avoid subclassing multiple exception types altogether."
msgstr ""
"La mayoría de las excepciones integradas están implementadas en C por "
"eficiencia, vea: :source:`Objects/exceptions.c`.  Algunas tienen "
"distribuciones de memoria personalizadas, lo que hace imposible crear una "
"subclase que herede de múltiples tipos de excepciones. La distribución de "
"memoria de un tipo es un detalle de implementación y podría cambiar entre "
"versiones de Python, llevando a nuevos conflictos en el futuro.  Por lo "
"tanto, se recomienda evitar la herencia de múltiples tipos de excepción."

#: ../Doc/library/exceptions.rst:93
msgid "Base classes"
msgstr "Clases base"

#: ../Doc/library/exceptions.rst:95
msgid ""
"The following exceptions are used mostly as base classes for other "
"exceptions."
msgstr ""
"Las siguientes excepciones se utilizan principalmente como clases base para "
"otras excepciones."

#: ../Doc/library/exceptions.rst:99
msgid ""
"The base class for all built-in exceptions.  It is not meant to be directly "
"inherited by user-defined classes (for that, use :exc:`Exception`).  If :"
"func:`str` is called on an instance of this class, the representation of the "
"argument(s) to the instance are returned, or the empty string when there "
"were no arguments."
msgstr ""
"La clase base para todas las excepciones predefinidas. No está pensada para "
"ser heredada directamente por las clases definidas por el usuario (para eso, "
"use :exc:`Exception`). Si se llama a :func:`str` en una instancia de esta "
"clase, se retorna la representación de los argumentos de la instancia o la "
"cadena vacía cuando no había argumentos."

#: ../Doc/library/exceptions.rst:107
msgid ""
"The tuple of arguments given to the exception constructor.  Some built-in "
"exceptions (like :exc:`OSError`) expect a certain number of arguments and "
"assign a special meaning to the elements of this tuple, while others are "
"usually called only with a single string giving an error message."
msgstr ""
"La tupla de argumentos dada al constructor de excepción. Algunas excepciones "
"predefinidas (como :exc:`OSError`) esperan un cierto número de argumentos y "
"asignan un significado especial a los elementos de esta tupla, mientras que "
"otras normalmente se llaman solo con una sola cadena que da un mensaje de "
"error."

#: ../Doc/library/exceptions.rst:114
msgid ""
"This method sets *tb* as the new traceback for the exception and returns the "
"exception object.  It was more commonly used before the exception chaining "
"features of :pep:`3134` became available.  The following example shows how "
"we can convert an instance of ``SomeException`` into an instance of "
"``OtherException`` while preserving the traceback.  Once raised, the current "
"frame is pushed onto the traceback of the ``OtherException``, as would have "
"happened to the traceback of the original ``SomeException`` had we allowed "
"it to propagate to the caller. ::"
msgstr ""
"Este método establece *tb* como el nuevo rastreo para la excepción y retorna "
"el objeto de excepción. Se usaba con más frecuencia antes de que las "
"características de encadenamiento de excepciones de :pep:`3134` estuvieran "
"disponibles. El siguiente ejemplo muestra cómo podemos convertir una "
"instancia de ``SomeException`` en una instancia de ``OtherException`` "
"mientras se conserva el rastreo. Una vez generado, el marco actual se "
"inserta en el rastreo del ``OtherException``, como habría sucedido con el "
"rastreo del ``SomeException`` original si hubiéramos permitido que se "
"propagara al llamador. ::"

#: ../Doc/library/exceptions.rst:131
msgid ""
"Add the string ``note`` to the exception's notes which appear in the "
"standard traceback after the exception string. A :exc:`TypeError` is raised "
"if ``note`` is not a string."
msgstr ""
"Agrega la cadena ``note`` a las notas de la excepción, las cuales aparecen "
"en el rastreo después de la cadena de la excepción. Se lanza un :exc:"
"`TypeError` si ``note`` no es una cadena de caracteres."

#: ../Doc/library/exceptions.rst:139
msgid ""
"A list of the notes of this exception, which were added with :meth:"
"`add_note`. This attribute is created when :meth:`add_note` is called."
msgstr ""
"Una lista de las notas de esta excepción, las cuales fueron añadidas con el "
"método :meth:`add_note`. Este atributo es creado cuando se llama a :meth:"
"`add_note`."

#: ../Doc/library/exceptions.rst:147
msgid ""
"All built-in, non-system-exiting exceptions are derived from this class.  "
"All user-defined exceptions should also be derived from this class."
msgstr ""
"Todas las excepciones predefinidas *non-system-exiting*, que no salen del "
"sistema se derivan de esta clase. Todas las excepciones definidas por el "
"usuario también deben derivarse de esta clase."

#: ../Doc/library/exceptions.rst:153
msgid ""
"The base class for those built-in exceptions that are raised for various "
"arithmetic errors: :exc:`OverflowError`, :exc:`ZeroDivisionError`, :exc:"
"`FloatingPointError`."
msgstr ""
"La clase base para las excepciones predefinidas que se generan para varios "
"errores aritméticos: :exc:`OverflowError`, :exc:`ZeroDivisionError`, :exc:"
"`FloatingPointError`."

#: ../Doc/library/exceptions.rst:160
msgid ""
"Raised when a :ref:`buffer <bufferobjects>` related operation cannot be "
"performed."
msgstr ""
"Se genera cuando :ref:`buffer <bufferobjects>` no se puede realizar una "
"operación relacionada."

#: ../Doc/library/exceptions.rst:166
msgid ""
"The base class for the exceptions that are raised when a key or index used "
"on a mapping or sequence is invalid: :exc:`IndexError`, :exc:`KeyError`.  "
"This can be raised directly by :func:`codecs.lookup`."
msgstr ""
"La clase base para las excepciones que se generan cuando una clave o índice "
"utilizado en un mapa o secuencia que no es válido: :exc:`IndexError`, :exc:"
"`KeyError`. Esto se puede lanzar directamente por :func:`codecs.lookup`."

#: ../Doc/library/exceptions.rst:172
msgid "Concrete exceptions"
msgstr "Excepciones específicas"

#: ../Doc/library/exceptions.rst:174
msgid "The following exceptions are the exceptions that are usually raised."
msgstr ""
"Las siguientes excepciones son las excepciones que normalmente se generan."

#: ../Doc/library/exceptions.rst:180
msgid "Raised when an :keyword:`assert` statement fails."
msgstr ""
"Se genera cuando se produce un error en una instrucción :keyword:`assert`."

#: ../Doc/library/exceptions.rst:185
msgid ""
"Raised when an attribute reference (see :ref:`attribute-references`) or "
"assignment fails.  (When an object does not support attribute references or "
"attribute assignments at all, :exc:`TypeError` is raised.)"
msgstr ""
"Se genera cuando se produce un error en una referencia de atributo (ver :ref:"
"`attribute-references`) o la asignación falla. (Cuando un objeto no admite "
"referencias de atributos o asignaciones de atributos en absoluto, se genera :"
"exc:`TypeError`.)"

#: ../Doc/library/exceptions.rst:189
msgid ""
"The :attr:`name` and :attr:`obj` attributes can be set using keyword-only "
"arguments to the constructor. When set they represent the name of the "
"attribute that was attempted to be accessed and the object that was accessed "
"for said attribute, respectively."
msgstr ""
"Los atributos :attr:`name` y :attr:`obj` se pueden configurar utilizando "
"argumentos de solo palabras clave para el constructor. Cuando se establecen, "
"representan el nombre del atributo al que se intentó acceder y el objeto al "
"que se accedió para dicho atributo, respectivamente."

#: ../Doc/library/exceptions.rst:194
msgid "Added the :attr:`name` and :attr:`obj` attributes."
msgstr "Se agregaron los atributos :attr:`name` y :attr:`obj`."

#: ../Doc/library/exceptions.rst:199
msgid ""
"Raised when the :func:`input` function hits an end-of-file condition (EOF) "
"without reading any data. (N.B.: the :meth:`io.IOBase.read` and :meth:`io."
"IOBase.readline` methods return an empty string when they hit EOF.)"
msgstr ""
"Se genera cuando la función :func:`input` alcanza una condición de fin de "
"archivo (EOF) sin leer ningún dato. (Note que el :meth:`io. IOBase.read` y :"
"meth:`io.IOBase.readline` retornan una cadena vacía cuando llegan a EOF.)"

#: ../Doc/library/exceptions.rst:206
msgid "Not currently used."
msgstr "No se usa actualmente."

#: ../Doc/library/exceptions.rst:211
msgid ""
"Raised when a :term:`generator` or :term:`coroutine` is closed; see :meth:"
"`generator.close` and :meth:`coroutine.close`.  It directly inherits from :"
"exc:`BaseException` instead of :exc:`Exception` since it is technically not "
"an error."
msgstr ""
"Se genera cuando un :term:`generator` o :term:`coroutine` está cerrado; ver :"
"meth:`generator.close` y :meth:`coroutine.close`. Hereda directamente de :"
"exc:`BaseException` en lugar de :exc:`Exception` ya que técnicamente no es "
"un error."

#: ../Doc/library/exceptions.rst:219
msgid ""
"Raised when the :keyword:`import` statement has troubles trying to load a "
"module.  Also raised when the \"from list\" in ``from ... import`` has a "
"name that cannot be found."
msgstr ""
"Se genera cuando la instrucción :keyword:`import` tiene problemas al "
"intentar cargar un módulo. También se produce cuando la *from list* en "
"``from ... import`` tiene un nombre que no se puede encontrar."

#: ../Doc/library/exceptions.rst:223
msgid ""
"The :attr:`name` and :attr:`path` attributes can be set using keyword-only "
"arguments to the constructor. When set they represent the name of the module "
"that was attempted to be imported and the path to any file which triggered "
"the exception, respectively."
msgstr ""
"Los atributos :attr:`name` y :attr:`path` solo se pueden establecer "
"utilizando argumentos de palabra clave en el constructor. Cuando se "
"establece, representan el nombre del módulo que se intentó importar y la "
"ruta de acceso a cualquier archivo que desencadenó la excepción, "
"respectivamente."

#: ../Doc/library/exceptions.rst:228
msgid "Added the :attr:`name` and :attr:`path` attributes."
msgstr "Se han añadido los atributos :attr:`name` y :attr:`path`."

#: ../Doc/library/exceptions.rst:233
msgid ""
"A subclass of :exc:`ImportError` which is raised by :keyword:`import` when a "
"module could not be located.  It is also raised when ``None`` is found in :"
"data:`sys.modules`."
msgstr ""
"Una subclase de :exc:`ImportError` que se genera mediante :keyword:`import` "
"cuando no se pudo encontrar un módulo. También se genera cuando ``None`` se "
"encuentra en :data:`sys.modules`."

#: ../Doc/library/exceptions.rst:242
msgid ""
"Raised when a sequence subscript is out of range.  (Slice indices are "
"silently truncated to fall in the allowed range; if an index is not an "
"integer, :exc:`TypeError` is raised.)"
msgstr ""
"Se genera cuando un subíndice de secuencia está fuera del rango. (Los "
"índices de la rebanada son truncados silenciosamente para caer en el "
"intervalo permitido; si un índice no es un entero, se genera :exc:"
"`TypeError`.)"

#: ../Doc/library/exceptions.rst:251
msgid ""
"Raised when a mapping (dictionary) key is not found in the set of existing "
"keys."
msgstr ""
"Se genera cuando no se encuentra una clave de asignación (diccionario) en el "
"conjunto de claves existentes (mapa)."

#: ../Doc/library/exceptions.rst:258
msgid ""
"Raised when the user hits the interrupt key (normally :kbd:`Control-C` or :"
"kbd:`Delete`).  During execution, a check for interrupts is made regularly. "
"The exception inherits from :exc:`BaseException` so as to not be "
"accidentally caught by code that catches :exc:`Exception` and thus prevent "
"the interpreter from exiting."
msgstr ""
"Se genera cuando el usuario pulsa la tecla de interrupción (normalmente :kbd:"
"`Control-C` o :kbd:`Delete`). Durante la ejecución, se realiza una "
"comprobación de interrupciones con regularidad. La excepción hereda de :exc:"
"`BaseException` para no ser detectada de forma accidental por :exc:"
"`Exception` y, por lo tanto, prevenir que el intérprete salga."

#: ../Doc/library/exceptions.rst:266
msgid ""
"Catching a :exc:`KeyboardInterrupt` requires special consideration. Because "
"it can be raised at unpredictable points, it may, in some circumstances, "
"leave the running program in an inconsistent state. It is generally best to "
"allow :exc:`KeyboardInterrupt` to end the program as quickly as possible or "
"avoid raising it entirely. (See :ref:`handlers-and-exceptions`.)"
msgstr ""
"Capturar una :exc:`KeyboardInterrupt` requiere especial consideración. "
"Debido a que puede ser lanzada en puntos impredecibles, puede, en algunas "
"circunstancias, dejar al programa en ejecución en un estado inconsistente. "
"Por lo general, es mejor permitir que :exc:`KeyboardInterrupt` termine el "
"programa tan pronto como sea o evitar lanzarla por completo. (Vea :ref:"
"`handlers-and-exceptions`.)"

#: ../Doc/library/exceptions.rst:276
msgid ""
"Raised when an operation runs out of memory but the situation may still be "
"rescued (by deleting some objects).  The associated value is a string "
"indicating what kind of (internal) operation ran out of memory. Note that "
"because of the underlying memory management architecture (C's :c:func:"
"`malloc` function), the interpreter may not always be able to completely "
"recover from this situation; it nevertheless raises an exception so that a "
"stack traceback can be printed, in case a run-away program was the cause."
msgstr ""
"Se genera cuando una operación se queda sin memoria pero la situación aún "
"puede ser recuperada (eliminando algunos objetos). El valor asociado es una "
"cadena que indica que tipo de operación (interna) se quedó sin memoria. "
"Tenga en cuenta que debido a la arquitectura de administración de memoria "
"(función :c:func:`malloc` de C), el intérprete no siempre puede recuperarse "
"completamente de esta situación; sin embargo, plantea una excepción para que "
"se pueda imprimir un seguimiento de la pila, en caso de que un programa "
"fuera de servicio fuera lo causa."

#: ../Doc/library/exceptions.rst:287
msgid ""
"Raised when a local or global name is not found.  This applies only to "
"unqualified names.  The associated value is an error message that includes "
"the name that could not be found."
msgstr ""
"Se genera cuando no se encuentra un nombre local o global. Esto se aplica "
"solo a nombres no calificados. El valor asociado es un mensaje de error que "
"incluye el nombre que no se pudo encontrar."

#: ../Doc/library/exceptions.rst:291
msgid ""
"The :attr:`name` attribute can be set using a keyword-only argument to the "
"constructor. When set it represent the name of the variable that was "
"attempted to be accessed."
msgstr ""
"El atributo :attr:`name` se puede establecer utilizando un argumento de solo "
"palabra clave para el constructor. Cuando se establece, representa el nombre "
"de la variable a la que se intentó acceder."

#: ../Doc/library/exceptions.rst:295
msgid "Added the :attr:`name` attribute."
msgstr "Se agregó el atributo :attr:`name`."

#: ../Doc/library/exceptions.rst:301
msgid ""
"This exception is derived from :exc:`RuntimeError`.  In user defined base "
"classes, abstract methods should raise this exception when they require "
"derived classes to override the method, or while the class is being "
"developed to indicate that the real implementation still needs to be added."
msgstr ""
"Esta excepción se deriva de :exc:`RuntimeError`. En las clases base "
"definidas por el usuario, los métodos abstractos deberían lanzar esta "
"excepción cuando requieren clases derivadas para anular el método, o "
"mientras se desarrolla la clase para indicar que la implementación real aún "
"necesita ser agregada."

#: ../Doc/library/exceptions.rst:308
msgid ""
"It should not be used to indicate that an operator or method is not meant to "
"be supported at all -- in that case either leave the operator / method "
"undefined or, if a subclass, set it to :data:`None`."
msgstr ""
"No debe usarse para indicar que un operador o método no debe ser admitido en "
"absoluto -- en ese caso, deje el operador / método sin definir o, si es una "
"subclase, se establece en :data:`None`."

#: ../Doc/library/exceptions.rst:314
msgid ""
"``NotImplementedError`` and ``NotImplemented`` are not interchangeable, even "
"though they have similar names and purposes.  See :data:`NotImplemented` for "
"details on when to use it."
msgstr ""
"``NotImplementedError`` y ``NotImplemented`` no son intercambiables, a pesar "
"de que tienen nombres y propósitos similares. Consulte :data:"
"`NotImplemented` para obtener detalles sobre cuándo usarlo."

#: ../Doc/library/exceptions.rst:323
msgid ""
"This exception is raised when a system function returns a system-related "
"error, including I/O failures such as \"file not found\" or \"disk "
"full\" (not for illegal argument types or other incidental errors)."
msgstr ""
"Esta excepción se produce cuando una función del sistema retorna un error "
"relacionado con el sistema, que incluye fallas de E/S como ``file not "
"found`` o ``disk full`` (no para tipos de argumentos ilegales u otros "
"errores incidentales)."

#: ../Doc/library/exceptions.rst:327
msgid ""
"The second form of the constructor sets the corresponding attributes, "
"described below.  The attributes default to :const:`None` if not specified.  "
"For backwards compatibility, if three arguments are passed, the :attr:"
"`~BaseException.args` attribute contains only a 2-tuple of the first two "
"constructor arguments."
msgstr ""
"La segunda forma del constructor establece los atributos correspondientes, "
"que se describen a continuación. Los atributos predeterminados son :const:"
"`None` si no se especifican. Para compatibilidad con versiones anteriores, "
"si se pasan tres argumentos, el atributo :attr:`~BaseException.args` "
"contiene solo una tupla de 2 de los dos primeros argumentos del constructor."

#: ../Doc/library/exceptions.rst:333
msgid ""
"The constructor often actually returns a subclass of :exc:`OSError`, as "
"described in `OS exceptions`_ below.  The particular subclass depends on the "
"final :attr:`.errno` value.  This behaviour only occurs when constructing :"
"exc:`OSError` directly or via an alias, and is not inherited when "
"subclassing."
msgstr ""
"El constructor a menudo retorna una subclase de :exc:`OSError`, como se "
"describe en `OS exceptions`_ a continuación. La subclase particular depende "
"del valor final :attr:`.errno`. Este comportamiento solo ocurre cuando se "
"construye :exc:`OSError` directamente o mediante un alias, y no se hereda al "
"derivar."

#: ../Doc/library/exceptions.rst:341
msgid "A numeric error code from the C variable :c:data:`errno`."
msgstr "Un código de error numérico de la variable C, :c:data:`errno`."

#: ../Doc/library/exceptions.rst:345
msgid ""
"Under Windows, this gives you the native Windows error code.  The :attr:`."
"errno` attribute is then an approximate translation, in POSIX terms, of that "
"native error code."
msgstr ""
"En Windows, esto le proporciona el código de error nativo de Windows. El "
"atributo :attr:`.errno` es entonces una traducción aproximada, en términos "
"POSIX, de ese código de error nativo."

#: ../Doc/library/exceptions.rst:349
msgid ""
"Under Windows, if the *winerror* constructor argument is an integer, the :"
"attr:`.errno` attribute is determined from the Windows error code, and the "
"*errno* argument is ignored.  On other platforms, the *winerror* argument is "
"ignored, and the :attr:`winerror` attribute does not exist."
msgstr ""
"En Windows, si el argumento del constructor ``winerror`` es un entero, el "
"atributo :attr:`.errno` se determina a partir del código de error de Windows "
"y el argumento ``errno`` se ignora. En otras plataformas, el argumento "
"``winerror`` se ignora y el atributo :attr:`winerror` no existe."

#: ../Doc/library/exceptions.rst:357
msgid ""
"The corresponding error message, as provided by the operating system.  It is "
"formatted by the C functions :c:func:`perror` under POSIX, and :c:func:"
"`FormatMessage` under Windows."
msgstr ""
"El mensaje de error correspondiente, tal como lo proporciona el sistema "
"operativo. Está formateado por las funciones de C, :c:func:`perror` en "
"POSIX, y :c:func:`FormatMessage` en Windows."

#: ../Doc/library/exceptions.rst:365
msgid ""
"For exceptions that involve a file system path (such as :func:`open` or :"
"func:`os.unlink`), :attr:`filename` is the file name passed to the function. "
"For functions that involve two file system paths (such as :func:`os."
"rename`), :attr:`filename2` corresponds to the second file name passed to "
"the function."
msgstr ""
"Para las excepciones que involucran una ruta del sistema de archivos (como :"
"func:`open` o :func:`os.unlink`), :attr:`filename` es el nombre del archivo "
"pasado a la función. Para las funciones que involucran dos rutas del sistema "
"de archivos (como :func:`os.rename`), :attr:`filename2` corresponde al "
"segundo nombre de archivo pasado a la función."

#: ../Doc/library/exceptions.rst:372
msgid ""
":exc:`EnvironmentError`, :exc:`IOError`, :exc:`WindowsError`, :exc:`socket."
"error`, :exc:`select.error` and :exc:`mmap.error` have been merged into :exc:"
"`OSError`, and the constructor may return a subclass."
msgstr ""
":exc:`EnvironmentError`, :exc:`IOError`, :exc:`WindowsError`, :exc:`socket."
"error`, :exc:`select.error` y :exc:`mmap.error` se han fusionado en :exc:"
"`OSError`, y el constructor puede retornar una subclase."

#: ../Doc/library/exceptions.rst:378
msgid ""
"The :attr:`filename` attribute is now the original file name passed to the "
"function, instead of the name encoded to or decoded from the :term:"
"`filesystem encoding and error handler`. Also, the *filename2* constructor "
"argument and attribute was added."
msgstr ""
"El atributo :attr:`filename` es ahora el nombre de archivo original pasado a "
"la función, en lugar del nombre codificado o decodificado desde :term:"
"`filesystem encoding and error handler`. Además, se agregaron el argumento y "
"atributo del constructor *filename2*."

#: ../Doc/library/exceptions.rst:387
msgid ""
"Raised when the result of an arithmetic operation is too large to be "
"represented.  This cannot occur for integers (which would rather raise :exc:"
"`MemoryError` than give up).  However, for historical reasons, OverflowError "
"is sometimes raised for integers that are outside a required range.   "
"Because of the lack of standardization of floating point exception handling "
"in C, most floating point operations are not checked."
msgstr ""
"Se genera cuando el resultado de una operación aritmética es demasiado "
"grande para ser representado. Esto no puede ocurrir para los enteros (para "
"lo cual es mejor lanzar :exc:`MemoryError` que darse por vencido). Sin "
"embargo, por razones históricas, ``OverflowError`` a veces se genera para "
"enteros que están fuera del rango requerido. Debido a la falta de "
"estandarización del manejo de excepciones de coma flotante en C, la mayoría "
"de las operaciones de coma flotante no se verifican."

#: ../Doc/library/exceptions.rst:397
msgid ""
"This exception is derived from :exc:`RuntimeError`.  It is raised when the "
"interpreter detects that the maximum recursion depth (see :func:`sys."
"getrecursionlimit`) is exceeded."
msgstr ""
"Esta excepción se deriva de :exc:`RuntimeError`. Se lanza cuando el "
"intérprete detecta que se excede la profundidad máxima de recursión (ver :"
"func:`sys.getrecursionlimit`)."

#: ../Doc/library/exceptions.rst:401
msgid "Previously, a plain :exc:`RuntimeError` was raised."
msgstr "Anteriormente, se planteó un simple :exc:`RuntimeError`."

#: ../Doc/library/exceptions.rst:407
msgid ""
"This exception is raised when a weak reference proxy, created by the :func:"
"`weakref.proxy` function, is used to access an attribute of the referent "
"after it has been garbage collected. For more information on weak "
"references, see the :mod:`weakref` module."
msgstr ""
"Esta excepción se produce cuando un proxy de referencia débil, creado por la "
"función :func:`weakref.proxy`, se utiliza para acceder a un atributo del "
"referente después de que se ha recolectado basura. Para obtener más "
"información sobre referencias débiles, consulte el módulo :mod:`weakref` ."

#: ../Doc/library/exceptions.rst:415
msgid ""
"Raised when an error is detected that doesn't fall in any of the other "
"categories.  The associated value is a string indicating what precisely went "
"wrong."
msgstr ""
"Se genera cuando se detecta un error que no corresponde a ninguna de las "
"otras categorías. El valor asociado es una cadena que indica exactamente qué "
"salió mal."

#: ../Doc/library/exceptions.rst:422
msgid ""
"Raised by built-in function :func:`next` and an :term:`iterator`\\'s :meth:"
"`~iterator.__next__` method to signal that there are no further items "
"produced by the iterator."
msgstr ""
"Generado por la función incorporada :func:`next` y un :term:`iterator`\\'s :"
"meth:`~iterator.__next__` para indicar que no hay más elementos producidos "
"por el iterador."

#: ../Doc/library/exceptions.rst:426
msgid ""
"The exception object has a single attribute :attr:`value`, which is given as "
"an argument when constructing the exception, and defaults to :const:`None`."
msgstr ""
"El objeto de excepción tiene un solo atributo :attr:`value`, que se "
"proporciona como argumento al construir la excepción, y por defecto es :"
"const:`None`."

#: ../Doc/library/exceptions.rst:430
msgid ""
"When a :term:`generator` or :term:`coroutine` function returns, a new :exc:"
"`StopIteration` instance is raised, and the value returned by the function "
"is used as the :attr:`value` parameter to the constructor of the exception."
msgstr ""
"Cuando se retorna una función :term:`generator` o :term:`coroutine`, se "
"genera una nueva instancia :exc:`StopIteration`, y el valor retornado por la "
"función se utiliza como parámetro :attr:`value` para constructor de la "
"excepción."

#: ../Doc/library/exceptions.rst:435
msgid ""
"If a generator code directly or indirectly raises :exc:`StopIteration`, it "
"is converted into a :exc:`RuntimeError` (retaining the :exc:`StopIteration` "
"as the new exception's cause)."
msgstr ""
"Si un generador lanza directa o indirectamente :exc:`StopIteration`, se "
"convierte en :exc:`RuntimeError` (conservando :exc:`StopIteration` como la "
"causa de la nueva excepción)."

#: ../Doc/library/exceptions.rst:439
msgid ""
"Added ``value`` attribute and the ability for generator functions to use it "
"to return a value."
msgstr ""
"Se agregó el atributo `*value*` y la capacidad de las funciones del "
"generador de usarlo para retornar un valor."

#: ../Doc/library/exceptions.rst:443
msgid ""
"Introduced the RuntimeError transformation via ``from __future__ import "
"generator_stop``, see :pep:`479`."
msgstr ""
"Introdujo la transformación *RuntimeError* a través de ``from __future__ "
"import generator_stop``, ver :pep:`479`."

#: ../Doc/library/exceptions.rst:447
msgid ""
"Enable :pep:`479` for all code by default: a :exc:`StopIteration` error "
"raised in a generator is transformed into a :exc:`RuntimeError`."
msgstr ""
"Habilitar :pep:`479` para todo el código por defecto: a :exc:`StopIteration` "
"generado en un generador se transforma en :exc:`RuntimeError`."

#: ../Doc/library/exceptions.rst:453
msgid ""
"Must be raised by :meth:`__anext__` method of an :term:`asynchronous "
"iterator` object to stop the iteration."
msgstr ""
"Se debe lanzar mediante :meth:`__anext__` de un objeto :term:`asynchronous "
"iterator` para detener la iteración."

#: ../Doc/library/exceptions.rst:460
msgid ""
"Raised when the parser encounters a syntax error.  This may occur in an :"
"keyword:`import` statement, in a call to the built-in functions :func:"
"`compile`, :func:`exec`, or :func:`eval`, or when reading the initial script "
"or standard input (also interactively)."
msgstr ""
"Se genera cuando el analizador encuentra un error de sintaxis. Esto puede "
"ocurrir en una instrucción :keyword:`import`, en una llamada a las funciones "
"integradas :func:`compile`, :func:`exec` o :func:`eval`, o al leer el script "
"inicial o la entrada estándar (también de forma interactiva)."

#: ../Doc/library/exceptions.rst:466
msgid ""
"The :func:`str` of the exception instance returns only the error message. "
"Details is a tuple whose members are also available as separate attributes."
msgstr ""
"El :func:`str` de la instancia de excepción retorna solo el mensaje de "
"error. Detalles es una tupla cuyos miembros también están disponibles como "
"atributos separados."

#: ../Doc/library/exceptions.rst:471
msgid "The name of the file the syntax error occurred in."
msgstr "El nombre del archivo en el que se produjo el error de sintaxis."

#: ../Doc/library/exceptions.rst:475
msgid ""
"Which line number in the file the error occurred in. This is 1-indexed: the "
"first line in the file has a ``lineno`` of 1."
msgstr ""
"En qué número de línea del archivo se produjo el error. Tiene un índice 1: "
"la primera línea del archivo tiene un ``lineno`` de 1."

#: ../Doc/library/exceptions.rst:480
msgid ""
"The column in the line where the error occurred. This is 1-indexed: the "
"first character in the line has an ``offset`` of 1."
msgstr ""
"La columna de la línea donde ocurrió el error. Está indexado a 1: el primer "
"carácter de la línea tiene un ``offset`` de 1."

#: ../Doc/library/exceptions.rst:485
msgid "The source code text involved in the error."
msgstr "El texto del código fuente involucrado en el error."

#: ../Doc/library/exceptions.rst:489
msgid ""
"Which line number in the file the error occurred ends in. This is 1-indexed: "
"the first line in the file has a ``lineno`` of 1."
msgstr ""
"En qué número de línea del archivo termina el error. Está indexado a 1: la "
"primera línea del archivo tiene un ``lineno`` de 1."

#: ../Doc/library/exceptions.rst:494
msgid ""
"The column in the end line where the error occurred finishes. This is 1-"
"indexed: the first character in the line has an ``offset`` of 1."
msgstr ""
"Finaliza la columna de la línea final donde ocurrió el error. Está indexado "
"a 1: el primer carácter de la línea tiene un ``offset`` de 1."

#: ../Doc/library/exceptions.rst:497
msgid ""
"For errors in f-string fields, the message is prefixed by \"f-string: \" and "
"the offsets are offsets in a text constructed from the replacement "
"expression.  For example, compiling f'Bad {a b} field' results in this args "
"attribute: ('f-string: ...', ('', 1, 2, '(a b)\\n', 1, 5))."
msgstr ""
"Para errores en los campos de cadena f, el mensaje tiene el prefijo \"cadena "
"f:\" y las compensaciones son compensaciones en un texto construido a partir "
"de la expresión de reemplazo. Por ejemplo, compilar f'Bad {ab} field 'da "
"como resultado este atributo args: (' f-string: ... ', (' ', 1, 2,' (ab) \\ "
"n ', 1, 5)) ."

#: ../Doc/library/exceptions.rst:502
msgid "Added the :attr:`end_lineno` and :attr:`end_offset` attributes."
msgstr "Se agregaron los atributos :attr:`end_lineno` y :attr:`end_offset`."

#: ../Doc/library/exceptions.rst:507
msgid ""
"Base class for syntax errors related to incorrect indentation.  This is a "
"subclass of :exc:`SyntaxError`."
msgstr ""
"Clase base para errores de sintaxis relacionados con sangría incorrecta. "
"Esta es una subclase de :exc:`SyntaxError`."

#: ../Doc/library/exceptions.rst:513
msgid ""
"Raised when indentation contains an inconsistent use of tabs and spaces. "
"This is a subclass of :exc:`IndentationError`."
msgstr ""
"Se genera cuando la sangría contiene un uso inconsistente de pestañas y "
"espacios. Esta es una subclase de :exc:`IndentationError`."

#: ../Doc/library/exceptions.rst:519
msgid ""
"Raised when the interpreter finds an internal error, but the situation does "
"not look so serious to cause it to abandon all hope. The associated value is "
"a string indicating what went wrong (in low-level terms)."
msgstr ""
"Se genera cuando el intérprete encuentra un error interno, pero la situación "
"no parece tan grave como para abandonar toda esperanza. El valor asociado es "
"una cadena que indica qué salió mal (a bajo nivel)."

#: ../Doc/library/exceptions.rst:523
msgid ""
"You should report this to the author or maintainer of your Python "
"interpreter. Be sure to report the version of the Python interpreter (``sys."
"version``; it is also printed at the start of an interactive Python "
"session), the exact error message (the exception's associated value) and if "
"possible the source of the program that triggered the error."
msgstr ""
"Debe informar esto al autor o responsable de su intérprete de Python. "
"Asegúrese de informar la versión del intérprete de Python (``sys.version``; "
"también se imprime al comienzo de una sesión interactiva de Python), el "
"mensaje de error exacto (el valor asociado de la excepción) y, si es "
"posible, la fuente del programa que activó el error."

#: ../Doc/library/exceptions.rst:532
msgid ""
"This exception is raised by the :func:`sys.exit` function.  It inherits "
"from :exc:`BaseException` instead of :exc:`Exception` so that it is not "
"accidentally caught by code that catches :exc:`Exception`.  This allows the "
"exception to properly propagate up and cause the interpreter to exit.  When "
"it is not handled, the Python interpreter exits; no stack traceback is "
"printed.  The constructor accepts the same optional argument passed to :func:"
"`sys.exit`. If the value is an integer, it specifies the system exit status "
"(passed to C's :c:func:`exit` function); if it is ``None``, the exit status "
"is zero; if it has another type (such as a string), the object's value is "
"printed and the exit status is one."
msgstr ""
"Esta excepción es provocada por la función :func:`sys.exit`. Hereda de :exc:"
"`BaseException` en lugar de :exc:`Exception` para que no sea gestionada "
"accidentalmente por el código que captura :exc:`Exception`. Esto permite que "
"la excepción se propague correctamente y que el intérprete salga. Cuando no "
"se maneja, el intérprete de Python sale; no se imprime el seguimiento de "
"pila. El constructor acepta el mismo argumento opcional pasado a :func:`sys."
"exit`. Si el valor es un entero, especifica el estado de salida del sistema "
"(se pasa a la función :c:func:`exit` de C); si es ``None``, el estado de "
"salida es cero; Si tiene otro tipo (como una cadena), se imprime el valor "
"del objeto y el estado de salida es uno."

#: ../Doc/library/exceptions.rst:543
msgid ""
"A call to :func:`sys.exit` is translated into an exception so that clean-up "
"handlers (:keyword:`finally` clauses of :keyword:`try` statements) can be "
"executed, and so that a debugger can execute a script without running the "
"risk of losing control.  The :func:`os._exit` function can be used if it is "
"absolutely positively necessary to exit immediately (for example, in the "
"child process after a call to :func:`os.fork`)."
msgstr ""
"Una llamada :func:`sys.exit` se traduce en una excepción para que los "
"gestores de limpieza (:keyword:`finally` cláusulas de :keyword:`try`) puedan "
"ejecutarse, y para que un depurador pueda ejecutar un *script* sin correr el "
"riesgo de perder el control. La función :func:`os._exit` se puede usar si es "
"absolutamente necesario salir (por ejemplo, en el proceso secundario después "
"de una llamada a :func:`os.fork`)."

#: ../Doc/library/exceptions.rst:552
msgid ""
"The exit status or error message that is passed to the constructor. "
"(Defaults to ``None``.)"
msgstr ""
"El estado de salida o mensaje de error que se pasa al constructor. (El valor "
"predeterminado es ``None``.)"

#: ../Doc/library/exceptions.rst:558
msgid ""
"Raised when an operation or function is applied to an object of "
"inappropriate type.  The associated value is a string giving details about "
"the type mismatch."
msgstr ""
"Se genera cuando una operación o función se aplica a un objeto de tipo "
"inapropiado. El valor asociado es una cadena que proporciona detalles sobre "
"la falta de coincidencia de tipos."

#: ../Doc/library/exceptions.rst:561
msgid ""
"This exception may be raised by user code to indicate that an attempted "
"operation on an object is not supported, and is not meant to be. If an "
"object is meant to support a given operation but has not yet provided an "
"implementation, :exc:`NotImplementedError` is the proper exception to raise."
msgstr ""
"El código de usuario puede lanzar esta excepción para indicar que un intento "
"de operación en un objeto no es compatible y no debe serlo. Si un objeto "
"está destinado a soportar una operación dada pero aún no ha proporcionado "
"una implementación, :exc:`NotImplementedError` es la excepción adecuada para "
"lanzar."

#: ../Doc/library/exceptions.rst:566
msgid ""
"Passing arguments of the wrong type (e.g. passing a :class:`list` when an :"
"class:`int` is expected) should result in a :exc:`TypeError`, but passing "
"arguments with the wrong value (e.g. a number outside expected boundaries) "
"should result in a :exc:`ValueError`."
msgstr ""
"Pasar argumentos del tipo incorrecto (por ejemplo, pasar a :class:`list` "
"cuando se espera un :class:`int`) debería dar como resultado :exc:"
"`TypeError`, pero pasar argumentos con el valor incorrecto (por ejemplo, un "
"número fuera límites esperados) debería dar como resultado :exc:`ValueError`."

#: ../Doc/library/exceptions.rst:573
msgid ""
"Raised when a reference is made to a local variable in a function or method, "
"but no value has been bound to that variable.  This is a subclass of :exc:"
"`NameError`."
msgstr ""
"Se genera cuando se hace referencia a una variable local en una función o "
"método, pero no se ha vinculado ningún valor a esa variable. Esta es una "
"subclase de :exc:`NameError`."

#: ../Doc/library/exceptions.rst:580
msgid ""
"Raised when a Unicode-related encoding or decoding error occurs.  It is a "
"subclass of :exc:`ValueError`."
msgstr ""
"Se genera cuando se produce un error de codificación o decodificación "
"relacionado con Unicode. Es una subclase de :exc:`ValueError`."

#: ../Doc/library/exceptions.rst:583
msgid ""
":exc:`UnicodeError` has attributes that describe the encoding or decoding "
"error.  For example, ``err.object[err.start:err.end]`` gives the particular "
"invalid input that the codec failed on."
msgstr ""
":exc:`UnicodeError` tiene atributos que describen el error de codificación o "
"decodificación. Por ejemplo, ``err.object[err.start:err.end]`` proporciona "
"la entrada inválida particular en la que falló el códec."

#: ../Doc/library/exceptions.rst:589
msgid "The name of the encoding that raised the error."
msgstr "El nombre de la codificación que provocó el error."

#: ../Doc/library/exceptions.rst:593
msgid "A string describing the specific codec error."
msgstr "Una cadena que describe el error de códec específico."

#: ../Doc/library/exceptions.rst:597
msgid "The object the codec was attempting to encode or decode."
msgstr "El objeto que el códec intentaba codificar o decodificar."

#: ../Doc/library/exceptions.rst:601
msgid "The first index of invalid data in :attr:`object`."
msgstr "El primer índice de datos no válidos en :attr:`object`."

#: ../Doc/library/exceptions.rst:605
msgid "The index after the last invalid data in :attr:`object`."
msgstr "El índice después de los últimos datos no válidos en :attr:`object`."

#: ../Doc/library/exceptions.rst:610
msgid ""
"Raised when a Unicode-related error occurs during encoding.  It is a "
"subclass of :exc:`UnicodeError`."
msgstr ""
"Se genera cuando se produce un error relacionado con Unicode durante la "
"codificación. Es una subclase de :exc:`UnicodeError`."

#: ../Doc/library/exceptions.rst:616
msgid ""
"Raised when a Unicode-related error occurs during decoding.  It is a "
"subclass of :exc:`UnicodeError`."
msgstr ""
"Se genera cuando se produce un error relacionado con Unicode durante la "
"codificación. Es una subclase de :exc:`UnicodeError`."

#: ../Doc/library/exceptions.rst:622
msgid ""
"Raised when a Unicode-related error occurs during translating.  It is a "
"subclass of :exc:`UnicodeError`."
msgstr ""
"Se genera cuando se produce un error relacionado con Unicode durante la "
"codificación. Es una subclase de :exc:`UnicodeError`."

#: ../Doc/library/exceptions.rst:628
msgid ""
"Raised when an operation or function receives an argument that has the right "
"type but an inappropriate value, and the situation is not described by a "
"more precise exception such as :exc:`IndexError`."
msgstr ""
"Se genera cuando una operación o función recibe un argumento que tiene el "
"tipo correcto pero un valor inapropiado, y la situación no se describe con "
"una excepción más precisa como :exc:`IndexError`."

#: ../Doc/library/exceptions.rst:635
msgid ""
"Raised when the second argument of a division or modulo operation is zero.  "
"The associated value is a string indicating the type of the operands and the "
"operation."
msgstr ""
"Se genera cuando el segundo argumento de una operación de división o módulo "
"es cero. El valor asociado es una cadena que indica el tipo de operandos y "
"la operación."

#: ../Doc/library/exceptions.rst:640
msgid ""
"The following exceptions are kept for compatibility with previous versions; "
"starting from Python 3.3, they are aliases of :exc:`OSError`."
msgstr ""
"Las siguientes excepciones se mantienen por compatibilidad con versiones "
"anteriores; a partir de Python 3.3, son alias de :exc:`OSError`."

#: ../Doc/library/exceptions.rst:649
msgid "Only available on Windows."
msgstr "Solo disponible en Windows."

#: ../Doc/library/exceptions.rst:653
msgid "OS exceptions"
msgstr "Excepciones del sistema operativo"

#: ../Doc/library/exceptions.rst:655
msgid ""
"The following exceptions are subclasses of :exc:`OSError`, they get raised "
"depending on the system error code."
msgstr ""
"Las siguientes excepciones son subclases de :exc:`OSError`, se generan según "
"el código de error del sistema."

#: ../Doc/library/exceptions.rst:660
msgid ""
"Raised when an operation would block on an object (e.g. socket) set for non-"
"blocking operation. Corresponds to :c:data:`errno` :py:data:`~errno."
"EAGAIN`, :py:data:`~errno.EALREADY`, :py:data:`~errno.EWOULDBLOCK` and :py:"
"data:`~errno.EINPROGRESS`."
msgstr ""
"Se lanza cuando una operación se bloquearía en un objeto (ejemplo: socket) "
"configurado para una operación no bloqueante. Corresponde a :c:data:`errno` :"
"py:data:`~errno.EAGAIN`, :py:data:`~errno.EALREADY`, :py:data:`~errno."
"EWOULDBLOCK` y :py:data:`~errno.EINPROGRESS`."

#: ../Doc/library/exceptions.rst:665
msgid ""
"In addition to those of :exc:`OSError`, :exc:`BlockingIOError` can have one "
"more attribute:"
msgstr ""
"Además de los de :exc:`OSError`, :exc:`BlockingIOError` puede tener un "
"atributo más:"

#: ../Doc/library/exceptions.rst:670
msgid ""
"An integer containing the number of characters written to the stream before "
"it blocked.  This attribute is available when using the buffered I/O classes "
"from the :mod:`io` module."
msgstr ""
"Un entero que contiene el número de caracteres escritos en la secuencia "
"antes de que se bloquee. Este atributo está disponible cuando se utilizan "
"las clases de E/S almacenadas en el modulo :mod:`io`."

#: ../Doc/library/exceptions.rst:676
msgid ""
"Raised when an operation on a child process failed. Corresponds to :c:data:"
"`errno` :py:data:`~errno.ECHILD`."
msgstr ""
"Se genera cuando falla una operación en un proceso secundario. Corresponde "
"a :c:data:`errno` :py:data:`~errno.ECHILD`."

#: ../Doc/library/exceptions.rst:681
msgid "A base class for connection-related issues."
msgstr "Una clase base para problemas relacionados con la conexión."

#: ../Doc/library/exceptions.rst:683
msgid ""
"Subclasses are :exc:`BrokenPipeError`, :exc:`ConnectionAbortedError`, :exc:"
"`ConnectionRefusedError` and :exc:`ConnectionResetError`."
msgstr ""
"Las subclases son :exc:`BrokenPipeError`, :exc:`ConnectionAbortedError`, :"
"exc:`ConnectionRefusedError` y :exc:`ConnectionResetError`."

#: ../Doc/library/exceptions.rst:688
msgid ""
"A subclass of :exc:`ConnectionError`, raised when trying to write on a pipe "
"while the other end has been closed, or trying to write on a socket which "
"has been shutdown for writing. Corresponds to :c:data:`errno` :py:data:"
"`~errno.EPIPE` and :py:data:`~errno.ESHUTDOWN`."
msgstr ""
"Una subclase de :exc:`ConnectionError`, que se genera cuando se intenta "
"escribir en una tubería mientras el otro extremo se ha cerrado, o cuando se "
"intenta escribir en un *socket* que se ha cerrado por escritura. Corresponde "
"a :c:data:`errno` :py:data:`~errno.EPIPE` y :py:data:`~errno.ESHUTDOWN`."

#: ../Doc/library/exceptions.rst:695
msgid ""
"A subclass of :exc:`ConnectionError`, raised when a connection attempt is "
"aborted by the peer. Corresponds to :c:data:`errno` :py:data:`~errno."
"ECONNABORTED`."
msgstr ""
"Una subclase de :exc:`ConnectionError`, que se genera cuando el par "
"interrumpe un intento de conexión. Corresponde a :c:data:`errno` :py:data:"
"`~errno.ECONNABORTED`."

#: ../Doc/library/exceptions.rst:701
msgid ""
"A subclass of :exc:`ConnectionError`, raised when a connection attempt is "
"refused by the peer. Corresponds to :c:data:`errno` :py:data:`~errno."
"ECONNREFUSED`."
msgstr ""
"Una subclase de :exc:`ConnectionError`, que se genera cuando el par "
"interrumpe un intento de conexión. Corresponde a :c:data:`errno` :py:data:"
"`~errno.ECONNREFUSED`."

#: ../Doc/library/exceptions.rst:707
msgid ""
"A subclass of :exc:`ConnectionError`, raised when a connection is reset by "
"the peer. Corresponds to :c:data:`errno` :py:data:`~errno.ECONNRESET`."
msgstr ""
"Una subclase de :exc:`ConnectionError`, que se genera cuando el par "
"restablece una conexión. Corresponde a :c:data:`errno` :py:data:`~errno."
"ECONNRESET`."

#: ../Doc/library/exceptions.rst:713
msgid ""
"Raised when trying to create a file or directory which already exists. "
"Corresponds to :c:data:`errno` :py:data:`~errno.EEXIST`."
msgstr ""
"Se genera al intentar crear un archivo o directorio que ya existe. "
"Corresponde a :c:data:`errno` :py:data:`~errno.EEXIST`."

#: ../Doc/library/exceptions.rst:718
msgid ""
"Raised when a file or directory is requested but doesn't exist. Corresponds "
"to :c:data:`errno` :py:data:`~errno.ENOENT`."
msgstr ""
"Se genera cuando se solicita un archivo o directorio pero no existe. "
"Corresponde a :c:data:`errno` :py:data:`~errno.ENOENT`."

#: ../Doc/library/exceptions.rst:723
msgid ""
"Raised when a system call is interrupted by an incoming signal. Corresponds "
"to :c:data:`errno` :py:data:`~errno.EINTR`."
msgstr ""
"Se genera cuando una llamada entrante interrumpe una llamada del sistema. "
"Corresponde a :c:data:`errno` :py:data:`~errno.EINTR`."

#: ../Doc/library/exceptions.rst:726
msgid ""
"Python now retries system calls when a syscall is interrupted by a signal, "
"except if the signal handler raises an exception (see :pep:`475` for the "
"rationale), instead of raising :exc:`InterruptedError`."
msgstr ""
"Python ahora vuelve a intentar las llamadas del sistema cuando una señal "
"interrumpe un *syscall*, excepto si el gestor de señales lanza una excepción "
"(ver :pep:`475` para la justificación), en lugar de lanzar :exc:"
"`InterruptedError`."

#: ../Doc/library/exceptions.rst:733
msgid ""
"Raised when a file operation (such as :func:`os.remove`) is requested on a "
"directory. Corresponds to :c:data:`errno` :py:data:`~errno.EISDIR`."
msgstr ""
"Se genera cuando se solicita una operación de archivo (como :func:`os."
"remove`) en un directorio. Corresponde a: :c:data:`errno` :py:data:`~errno."
"EISDIR`."

#: ../Doc/library/exceptions.rst:739
msgid ""
"Raised when a directory operation (such as :func:`os.listdir`) is requested "
"on something which is not a directory.  On most POSIX platforms, it may also "
"be raised if an operation attempts to open or traverse a non-directory file "
"as if it were a directory. Corresponds to :c:data:`errno` :py:data:`~errno."
"ENOTDIR`."
msgstr ""
"Se genera cuando se solicita una operación de directorio (como :func:`os."
"listdir`) en algo que no es un directorio.  En la mayoría de las plataformas "
"POSIX, también se puede lanzar si una operación intenta abrir o recorrer un "
"archivo que no es de directorio como si fuera un directorio. Corresponde a :"
"c:data:`errno` :py:data:`~errno.ENOTDIR`."

#: ../Doc/library/exceptions.rst:747
msgid ""
"Raised when trying to run an operation without the adequate access rights - "
"for example filesystem permissions. Corresponds to :c:data:`errno` :py:data:"
"`~errno.EACCES`, :py:data:`~errno.EPERM`, and :py:data:`~errno.ENOTCAPABLE`."
msgstr ""
"Se genera cuando se intenta ejecutar una operación sin los permisos de "
"acceso adecuados - por ejemplo permisos del sistema de archivos. Corresponde "
"a :c:data:`errno` :py:data:`~errno.EACCES`, :py:data:`~errno.EPERM`, y :py:"
"data:`~errno.ENOTCAPABLE`."

#: ../Doc/library/exceptions.rst:752
msgid ""
"WASI's :py:data:`~errno.ENOTCAPABLE` is now mapped to :exc:`PermissionError`."
msgstr ""
"WASI's :py:data:`~errno.ENOTCAPABLE` ahora se mapea a :exc:`PermissionError`."

#: ../Doc/library/exceptions.rst:758
msgid ""
"Raised when a given process doesn't exist. Corresponds to :c:data:`errno` :"
"py:data:`~errno.ESRCH`."
msgstr ""
"Generado cuando un proceso dado no existe. Corresponde a :c:data:`errno` :py:"
"data:`~errno.ESRCH`."

#: ../Doc/library/exceptions.rst:763
msgid ""
"Raised when a system function timed out at the system level. Corresponds to :"
"c:data:`errno` :py:data:`~errno.ETIMEDOUT`."
msgstr ""
"Se genera cuando se agota el tiempo de espera de una función del sistema a "
"nivel del sistema. Corresponde a :c:data:`errno` :py:data:`~errno.ETIMEDOUT`."

#: ../Doc/library/exceptions.rst:766
msgid "All the above :exc:`OSError` subclasses were added."
msgstr "Por lo anterior se agregaron las subclases :exc:`OSError`."

#: ../Doc/library/exceptions.rst:772
msgid ":pep:`3151` - Reworking the OS and IO exception hierarchy"
msgstr ""
":pep:`3151` - Reelaborando el sistema operativo y la jerarquía de "
"excepciones E/S"

#: ../Doc/library/exceptions.rst:778
msgid "Warnings"
msgstr "Advertencias"

#: ../Doc/library/exceptions.rst:780
msgid ""
"The following exceptions are used as warning categories; see the :ref:"
"`warning-categories` documentation for more details."
msgstr ""
"Las siguientes excepciones se utilizan como categorías de advertencia; "
"consulte la documentación de :ref:`warning-categories` para obtener más "
"detalles."

#: ../Doc/library/exceptions.rst:785
msgid "Base class for warning categories."
msgstr "Clase base para categorías de advertencia."

#: ../Doc/library/exceptions.rst:790
msgid "Base class for warnings generated by user code."
msgstr "Clase base para advertencias generadas por código de usuario."

#: ../Doc/library/exceptions.rst:795
msgid ""
"Base class for warnings about deprecated features when those warnings are "
"intended for other Python developers."
msgstr ""
"Clase base para advertencias sobre características obsoletas cuando esas "
"advertencias están destinadas a otros desarrolladores de Python."

#: ../Doc/library/exceptions.rst:798
msgid ""
"Ignored by the default warning filters, except in the ``__main__`` module (:"
"pep:`565`). Enabling the :ref:`Python Development Mode <devmode>` shows this "
"warning."
msgstr ""
"Ignorado por los filtros de advertencia predeterminados, excepto en el "
"módulo ``__main__`` (:pep:`565`). Habilitando :ref:`Modo Desarrollo de "
"Python <devmode>` muestra esta advertencia."

#: ../Doc/library/exceptions.rst:802 ../Doc/library/exceptions.rst:818
msgid "The deprecation policy is described in :pep:`387`."
msgstr "La política de obsolescencia se describe en :pep:`387`."

#: ../Doc/library/exceptions.rst:807
msgid ""
"Base class for warnings about features which are obsolete and expected to be "
"deprecated in the future, but are not deprecated at the moment."
msgstr ""
"Clase base para advertencias sobre características que están obsoletas y que "
"se espera que sean obsoletas en el futuro, pero que no lo son en este "
"momento."

#: ../Doc/library/exceptions.rst:811
msgid ""
"This class is rarely used as emitting a warning about a possible upcoming "
"deprecation is unusual, and :exc:`DeprecationWarning` is preferred for "
"already active deprecations."
msgstr ""
"Esta clase rara vez se usa para emitir una advertencia sobre una posible "
"desaprobación próxima es inusual, y :exc:`DeprecationWarning` se prefiere "
"para las desaprobaciones ya activas."

#: ../Doc/library/exceptions.rst:815 ../Doc/library/exceptions.rst:841
#: ../Doc/library/exceptions.rst:868
msgid ""
"Ignored by the default warning filters. Enabling the :ref:`Python "
"Development Mode <devmode>` shows this warning."
msgstr ""
"Ignorado por los filtros de advertencia predeterminados. Habilitando :ref:"
"`Modo Desarrollo de Python <devmode>` muestra esta advertencia."

#: ../Doc/library/exceptions.rst:823
msgid "Base class for warnings about dubious syntax."
msgstr "Clase base para advertencias sobre sintaxis dudosa."

#: ../Doc/library/exceptions.rst:828
msgid "Base class for warnings about dubious runtime behavior."
msgstr ""
"Clase base para advertencias sobre comportamiento dudoso en tiempo de "
"ejecución."

#: ../Doc/library/exceptions.rst:833
msgid ""
"Base class for warnings about deprecated features when those warnings are "
"intended for end users of applications that are written in Python."
msgstr ""
"Clase base para advertencias sobre características en desuso cuando esas "
"advertencias están destinadas a usuarios finales de aplicaciones escritas en "
"Python."

#: ../Doc/library/exceptions.rst:839
msgid "Base class for warnings about probable mistakes in module imports."
msgstr ""
"Clase base para advertencias sobre posibles errores en la importación de "
"módulos."

#: ../Doc/library/exceptions.rst:847
msgid "Base class for warnings related to Unicode."
msgstr "Clase base para advertencias relacionadas con Unicode."

#: ../Doc/library/exceptions.rst:852
msgid "Base class for warnings related to encodings."
msgstr "Clase base para advertencias relacionadas con codificaciones."

#: ../Doc/library/exceptions.rst:854
msgid "See :ref:`io-encoding-warning` for details."
msgstr "Consulte :ref:`io-encoding-warning` para obtener más detalles."

#: ../Doc/library/exceptions.rst:861
msgid ""
"Base class for warnings related to :class:`bytes` and :class:`bytearray`."
msgstr ""
"Clase base para advertencias relacionadas con :class:`bytes` y :class:"
"`bytearray`."

#: ../Doc/library/exceptions.rst:866
msgid "Base class for warnings related to resource usage."
msgstr "Clase base para advertencias relacionadas con el uso de recursos."

#: ../Doc/library/exceptions.rst:875
msgid "Exception groups"
msgstr "Grupos de excepciones"

#: ../Doc/library/exceptions.rst:877
msgid ""
"The following are used when it is necessary to raise multiple unrelated "
"exceptions. They are part of the exception hierarchy so they can be handled "
"with :keyword:`except` like all other exceptions. In addition, they are "
"recognised by :keyword:`except*<except_star>`, which matches their subgroups "
"based on the types of the contained exceptions."
msgstr ""
"Las siguientes se utilizan cuando es necesario lanzar múltiples excepciones "
"no relacionadas. Forman parte de la jerarquía de excepciones, por lo que "
"pueden ser manejadas con :keyword:`except` como todas las demás excepciones. "
"Además, son reconocidas por :keyword:`except*<except_star>`, lo que hace "
"coincidir sus subgrupos basándose en los tipos de las excepciones contenidas."

#: ../Doc/library/exceptions.rst:886
msgid ""
"Both of these exception types wrap the exceptions in the sequence ``excs``. "
"The ``msg`` parameter must be a string. The difference between the two "
"classes is that :exc:`BaseExceptionGroup` extends :exc:`BaseException` and "
"it can wrap any exception, while :exc:`ExceptionGroup` extends :exc:"
"`Exception` and it can only wrap subclasses of :exc:`Exception`. This design "
"is so that ``except Exception`` catches an :exc:`ExceptionGroup` but not :"
"exc:`BaseExceptionGroup`."
msgstr ""
"Ambos tipos de excepción envuelven las excepciones en la secuencia ``excs``. "
"El parámetro ``msg`` debe ser una cadena de caracteres. La diferencia entre "
"las dos clases es que :exc:`BaseExceptionGroup` extiende a :exc:"
"`BaseException` y puede envolver cualquier excepción, mientras que :exc:"
"`ExceptionGroup` extiende a :exc:`Exception` y solo puede envolver subclases "
"de :exc:`Exception`. Este diseño está pensado para que ``except Exception`` "
"capture un :exc:`ExceptionGroup` pero no :exc:`BaseExceptionGroup`"

#: ../Doc/library/exceptions.rst:894
msgid ""
"The :exc:`BaseExceptionGroup` constructor returns an :exc:`ExceptionGroup` "
"rather than a :exc:`BaseExceptionGroup` if all contained exceptions are :exc:"
"`Exception` instances, so it can be used to make the selection automatic. "
"The :exc:`ExceptionGroup` constructor, on the other hand, raises a :exc:"
"`TypeError` if any contained exception is not an :exc:`Exception` subclass."
msgstr ""
"El constructor :exc:`BaseExceptionGroup` retorna una :exc:`ExceptionGroup` "
"en lugar de una :exc:`BaseExceptionGroup` si todas las excepciones "
"contenidas son instancias de :exc:`Exception` , por lo que puede utilizarse "
"para hacer la selección automática. El constructor :exc:`ExceptionGroup`, "
"por su parte, lanza un :exc:`TypeError` si alguna de las excepciones "
"contenidas no es una subclase de :exc:`Exception`."

#: ../Doc/library/exceptions.rst:903
msgid "The ``msg`` argument to the constructor. This is a read-only attribute."
msgstr ""
"El argumento ``msg`` para el constructor. Este atributo es de sólo lectura."

#: ../Doc/library/exceptions.rst:907
msgid ""
"A tuple of the exceptions in the ``excs`` sequence given to the constructor. "
"This is a read-only attribute."
msgstr ""
"Una tupla de la excepciones en la secuencia ``excs`` pasada al constructor. "
"Este atributo es de sólo lectura."

#: ../Doc/library/exceptions.rst:912
msgid ""
"Returns an exception group that contains only the exceptions from the "
"current group that match *condition*, or ``None`` if the result is empty."
msgstr ""
"Retorna un grupo de excepciones que contiene sólo las excepciones del grupo "
"actual que cumplen con *condition*, o ``None`` si el resultado está vacío."

#: ../Doc/library/exceptions.rst:915
msgid ""
"The condition can be either a function that accepts an exception and returns "
"true for those that should be in the subgroup, or it can be an exception "
"type or a tuple of exception types, which is used to check for a match using "
"the same check that is used in an ``except`` clause."
msgstr ""
"La condición puede ser una función que acepta una excepción y retorna *True* "
"para aquellas que deberían estar en el subgrupo, o puede ser un tipo de "
"excepción o una tupla de tipos de excepción, que se utiliza para comprobar "
"una coincidencia utilizando la misma comprobación que se utiliza en una "
"cláusula ``except``."

#: ../Doc/library/exceptions.rst:920
msgid ""
"The nesting structure of the current exception is preserved in the result, "
"as are the values of its :attr:`message`, :attr:`__traceback__`, :attr:"
"`__cause__`, :attr:`__context__` and :attr:`__notes__` fields. Empty nested "
"groups are omitted from the result."
msgstr ""
"La estructura de anidamiento de la excepción actual se conserva en el "
"resultado, así como también los valores de sus campos :attr:`message`, :attr:"
"`__traceback__`, :attr:`__cause__`, :attr:`__context__` y :attr:`__notes__`. "
"Los grupos anidados vacíos son omitidos del resultado."

#: ../Doc/library/exceptions.rst:925
msgid ""
"The condition is checked for all exceptions in the nested exception group, "
"including the top-level and any nested exception groups. If the condition is "
"true for such an exception group, it is included in the result in full."
msgstr ""
"La condición se comprueba para todas las excepciones del grupo de excepción "
"anidado, incluyendo el nivel superior y cualquier grupo de excepción "
"anidado. Si la condición es verdadera para dicho grupo de excepción, se "
"incluye en el resultado en su totalidad."

#: ../Doc/library/exceptions.rst:931
msgid ""
"Like :meth:`subgroup`, but returns the pair ``(match, rest)`` where "
"``match`` is ``subgroup(condition)`` and ``rest`` is the remaining non-"
"matching part."
msgstr ""
"Al igual que :meth:`subgroup`, pero retorna el par ``(match, rest)`` donde "
"``match`` es ``subgroup(condition)`` y ``rest`` es la parte restante que no "
"coincide."

#: ../Doc/library/exceptions.rst:937
msgid ""
"Returns an exception group with the same :attr:`message`, :attr:"
"`__traceback__`, :attr:`__cause__`, :attr:`__context__` and :attr:"
"`__notes__` but which wraps the exceptions in ``excs``."
msgstr ""
"Retorna un grupo de excepción con los mismos :attr:`message`, :attr:"
"`__traceback__`, :attr:`__cause__`, :attr:`__context__` y :attr:`__notes__` "
"pero que envuelve las excepciones en ``excs``."

#: ../Doc/library/exceptions.rst:941
msgid ""
"This method is used by :meth:`subgroup` and :meth:`split`. A subclass needs "
"to override it in order to make :meth:`subgroup` and :meth:`split` return "
"instances of the subclass rather than :exc:`ExceptionGroup`. ::"
msgstr ""
"Este método es usado por :meth:`subgroup` y :meth:`split`. Se necesita una "
"subclase que lo sobrescriba para que :meth:`subgroup` y :meth:`split` "
"retornan instancias de la subclase en lugar de :exc:`ExceptionGroup`. ::"

#: ../Doc/library/exceptions.rst:953
#, fuzzy
msgid ""
"Note that :exc:`BaseExceptionGroup` defines :meth:`__new__`, so subclasses "
"that need a different constructor signature need to override that rather "
"than :meth:`__init__`. For example, the following defines an exception group "
"subclass which accepts an exit_code and and constructs the group's message "
"from it. ::"
msgstr ""
"Nota que :exc:`BaseExceptionGroup` define :meth:`__new__`, por lo que las "
"subclases que necesiten una firma de constructor diferente deben "
"sobrescribir ese método en lugar de :`__init__`. Por ejemplo, lo siguiente "
"define una subclase de grupo de excepción que acepta un *exit_code* y "
"construye el mensaje del grupo a partir del mismo. ::"

#: ../Doc/library/exceptions.rst:972
msgid "Exception hierarchy"
msgstr "Jerarquía de excepción"

#: ../Doc/library/exceptions.rst:974
msgid "The class hierarchy for built-in exceptions is:"
msgstr "La jerarquía de clases para las excepciones incorporadas es:"

#~ msgid ""
#~ "When raising (or re-raising) an exception in an :keyword:`except` or :"
#~ "keyword:`finally` clause :attr:`__context__` is automatically set to the "
#~ "last exception caught; if the new exception is not handled the traceback "
#~ "that is eventually displayed will include the originating exception(s) "
#~ "and the final exception."
#~ msgstr ""
#~ "Al lanzar (o relanzar) una excepción en una clausula :keyword:`except` o :"
#~ "keyword:`finally` clausula :attr:`__context__` se establece "
#~ "automáticamente en la ultima excepción detectada; si no se controla la "
#~ "nueva excepción, el seguimiento que finalmente se muestra como resultado "
#~ "incluirá las excepciones de origen y la excepción final."

#~ msgid ""
#~ "Raised when an operation would block on an object (e.g. socket) set for "
#~ "non-blocking operation. Corresponds to :c:data:`errno` ``EAGAIN``, "
#~ "``EALREADY``, ``EWOULDBLOCK`` and ``EINPROGRESS``."
#~ msgstr ""
#~ "Se genera cuando una operación se bloquearía en un objeto (por ejemplo, "
#~ "un *socket*) configurado para una operación sin bloqueo. Corresponde a :c:"
#~ "data:`errno` ``EAGAIN``, ``EALREADY``, ``EWOULDBLOCK`` y ``EINPROGRESS``."

#~ msgid ""
#~ "Raised when trying to run an operation without the adequate access rights "
#~ "- for example filesystem permissions. Corresponds to :c:data:`errno` "
#~ "``EACCES`` and ``EPERM``."
#~ msgstr ""
#~ "Se genera cuando se intenta ejecutar una operación sin los derechos de "
#~ "acceso adecuados, por ejemplo, permisos del sistema de archivos. "
#~ "Corresponde a :c:data:`errno` ``EACCES`` y ``EPERM``."
