# Copyright (C) 2001-2020, Python Software Foundation
# This file is distributed under the same license as the Python package.
# Maintained by the python-doc-es workteam.
# docs-es@python.org /
# https://mail.python.org/mailman3/lists/docs-es.python.org/
# Check https://github.com/python/python-docs-es/blob/3.8/TRANSLATORS to get
# the list of volunteers
#
msgid ""
msgstr ""
"Project-Id-Version: Python 3.8\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-03-19 11:16+0100\n"
"PO-Revision-Date: 2020-05-20 10:03-0500\n"
"Last-Translator: \n"
"Language: es\n"
"Language-Team: python-doc-es\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.8.0\n"

#: ../Doc/library/exceptions.rst:4
msgid "Built-in Exceptions"
msgstr "Excepciones incorporadas"

#: ../Doc/library/exceptions.rst:10
msgid ""
"In Python, all exceptions must be instances of a class that derives from :"
"class:`BaseException`.  In a :keyword:`try` statement with an :keyword:"
"`except` clause that mentions a particular class, that clause also handles "
"any exception classes derived from that class (but not exception classes "
"from which *it* is derived).  Two exception classes that are not related via "
"subclassing are never equivalent, even if they have the same name."
msgstr ""
"En Python, todas las excepciones deben ser instancias de una clase que se "
"derive de :class:`BaseException`. En una instrucción :keyword:`try` con una "
"cláusula :keyword:`except` que menciona una clase determinada, esa cláusula "
"también controla las clases de excepción derivadas de esa clase (excepto las "
"clases de excepción de las que se deriva *it*). Dos clases de excepción que "
"no están relacionadas mediante subclases nunca son equivalentes, incluso si "
"tienen el mismo nombre."

#: ../Doc/library/exceptions.rst:19
msgid ""
"The built-in exceptions listed below can be generated by the interpreter or "
"built-in functions.  Except where mentioned, they have an \"associated value"
"\" indicating the detailed cause of the error.  This may be a string or a "
"tuple of several items of information (e.g., an error code and a string "
"explaining the code).  The associated value is usually passed as arguments "
"to the exception class's constructor."
msgstr ""
"Las excepciones predefinidas enumeradas a continuación pueden ser generadas "
"por el intérprete o funciones predefinidas. Excepto donde se mencione lo "
"contrario, tienen un *associated value* que indica la causa detallada del "
"error. Esto podría una cadena de caracteres o una tupla elementos con "
"grandes elementos de información (por ejemplo, un código de error y una "
"cadena que explica el código). El valor asociado generalmente se pasa como "
"argumentos al constructor de la clase de excepción."

#: ../Doc/library/exceptions.rst:26
msgid ""
"User code can raise built-in exceptions.  This can be used to test an "
"exception handler or to report an error condition \"just like\" the "
"situation in which the interpreter raises the same exception; but beware "
"that there is nothing to prevent user code from raising an inappropriate "
"error."
msgstr ""
"El código de usuario puede generar excepciones predefinidas. Esto puede ser "
"usado para probar un gestor de excepciones o para notificar una condición de "
"error \"igual\" a la situación en la cual el intérprete lance la misma "
"excepción; pero tenga en cuenta que no hay nada que impida que el código del "
"usuario produzca un error inapropiado."

#: ../Doc/library/exceptions.rst:31
msgid ""
"The built-in exception classes can be subclassed to define new exceptions; "
"programmers are encouraged to derive new exceptions from the :exc:"
"`Exception` class or one of its subclasses, and not from :exc:"
"`BaseException`.  More information on defining exceptions is available in "
"the Python Tutorial under :ref:`tut-userexceptions`."
msgstr ""
"Las clases de excepción predefinidas pueden ser usadas como subclases para "
"definir otras nuevas; se recomienda a los programadores que deriven nuevas "
"excepciones a partir de la clase :exc:`Exception` o de una de sus subclases, "
"y no de :exc:`BaseException`. Hay disponible más información sobre la "
"definición de excepciones en el Tutorial de Python en :ref:`tut-"
"userexceptions`."

#: ../Doc/library/exceptions.rst:37
msgid ""
"When raising (or re-raising) an exception in an :keyword:`except` or :"
"keyword:`finally` clause :attr:`__context__` is automatically set to the "
"last exception caught; if the new exception is not handled the traceback "
"that is eventually displayed will include the originating exception(s) and "
"the final exception."
msgstr ""
"Al lanzar (o relanzar) una excepción en una clausula :keyword:`except` o :"
"keyword:`finally` clausula :attr:`__context__` se establece automáticamente "
"en la ultima excepción detectada; si no se controla la nueva excepción, el "
"seguimiento que finalmente se muestra como resultado incluirá las "
"excepciones de origen y la excepción final."

#: ../Doc/library/exceptions.rst:43
msgid ""
"When raising a new exception (rather than using a bare ``raise`` to re-raise "
"the exception currently being handled), the implicit exception context can "
"be supplemented with an explicit cause by using :keyword:`from` with :"
"keyword:`raise`::"
msgstr ""
"Al lanzar una nueva excepción (en lugar de usar solamente ``raise`` para "
"relanzar la excepción que se esta manejando actualmente), el contexto de "
"excepción implícito se puede complementar con una causa explicita mediante :"
"keyword:`from` con :keyword:`raise`::"

#: ../Doc/library/exceptions.rst:50
msgid ""
"The expression following :keyword:`from` must be an exception or ``None``. "
"It will be set as :attr:`__cause__` on the raised exception. Setting :attr:"
"`__cause__` also implicitly sets the :attr:`__suppress_context__` attribute "
"to ``True``, so that using ``raise new_exc from None`` effectively replaces "
"the old exception with the new one for display purposes (e.g. converting :"
"exc:`KeyError` to :exc:`AttributeError`), while leaving the old exception "
"available in :attr:`__context__` for introspection when debugging."
msgstr ""
"La siguiente expresión :keyword:`from` tiene que ser una excepción o "
"``None``. Se establecerá como :attr:`__cause__` en la excepción planteada. "
"Ajustando :attr:`__cause__` también establece implícitamente el atributo :"
"attr:`__suppress_context__` a verdadero (*True*), de modo que el uso de la "
"``generacion new_exc from None`` reemplaza eficazmente la antigua excepción "
"con la nueva para fines de visualización (por ejemplo, convertir :exc:"
"`KeyError` a :exc:`AttributeError`), dejando la antigua excepción disponible "
"en :attr:`__context__` para introspección al depurar."

#: ../Doc/library/exceptions.rst:59
msgid ""
"The default traceback display code shows these chained exceptions in "
"addition to the traceback for the exception itself. An explicitly chained "
"exception in :attr:`__cause__` is always shown when present. An implicitly "
"chained exception in :attr:`__context__` is shown only if :attr:`__cause__` "
"is :const:`None` and :attr:`__suppress_context__` is false."
msgstr ""
"La visualización por defecto de la traza de error muestra estas excepciones "
"encadenadas además de la traza de la propia excepción. Siempre se muestra "
"una excepción encadenada explícitamente en :attr:`__cause__` cuando está "
"presente. Una excepción implícitamente encadenada en :attr:`__context__` "
"solo se muestra si :attr:`__cause__` es :const:`None` y :attr:"
"`__suppress_context__` es falso."

#: ../Doc/library/exceptions.rst:65
msgid ""
"In either case, the exception itself is always shown after any chained "
"exceptions so that the final line of the traceback always shows the last "
"exception that was raised."
msgstr ""
"En cualquier caso, la excepción en sí siempre se muestra después de "
"cualquier excepción encadenada para que la línea final del seguimiento "
"siempre muestre la última excepción que se generó."

#: ../Doc/library/exceptions.rst:71
msgid "Base classes"
msgstr "Clases base"

#: ../Doc/library/exceptions.rst:73
msgid ""
"The following exceptions are used mostly as base classes for other "
"exceptions."
msgstr ""
"Las siguientes excepciones se utilizan principalmente como clases base para "
"otras excepciones."

#: ../Doc/library/exceptions.rst:77
msgid ""
"The base class for all built-in exceptions.  It is not meant to be directly "
"inherited by user-defined classes (for that, use :exc:`Exception`).  If :"
"func:`str` is called on an instance of this class, the representation of the "
"argument(s) to the instance are returned, or the empty string when there "
"were no arguments."
msgstr ""
"La clase base para todas las excepciones predefinidas. No está pensada para "
"ser heredada directamente por las clases definidas por el usuario (para eso, "
"use :exc:`Exception`). Si se llama a :func:`str` en una instancia de esta "
"clase, se retorna la representación de los argumentos de la instancia o la "
"cadena vacía cuando no había argumentos."

#: ../Doc/library/exceptions.rst:85
msgid ""
"The tuple of arguments given to the exception constructor.  Some built-in "
"exceptions (like :exc:`OSError`) expect a certain number of arguments and "
"assign a special meaning to the elements of this tuple, while others are "
"usually called only with a single string giving an error message."
msgstr ""
"La tupla de argumentos dada al constructor de excepción. Algunas excepciones "
"predefinidas (como :exc:`OSError`) esperan un cierto número de argumentos y "
"asignan un significado especial a los elementos de esta tupla, mientras que "
"otras normalmente se llaman solo con una sola cadena que da un mensaje de "
"error."

#: ../Doc/library/exceptions.rst:92
msgid ""
"This method sets *tb* as the new traceback for the exception and returns the "
"exception object.  It is usually used in exception handling code like this::"
msgstr ""
"Este método establece ``tb`` como el nuevo ``traceback`` para la excepción y "
"retorna el objeto de excepción. Normalmente se utiliza en código de control "
"de excepciones como este::"

#: ../Doc/library/exceptions.rst:105
msgid ""
"All built-in, non-system-exiting exceptions are derived from this class.  "
"All user-defined exceptions should also be derived from this class."
msgstr ""
"Todas las excepciones predefinidas *non-system-exiting*, que no salen del "
"sistema se derivan de esta clase. Todas las excepciones definidas por el "
"usuario también deben derivarse de esta clase."

#: ../Doc/library/exceptions.rst:111
msgid ""
"The base class for those built-in exceptions that are raised for various "
"arithmetic errors: :exc:`OverflowError`, :exc:`ZeroDivisionError`, :exc:"
"`FloatingPointError`."
msgstr ""
"La clase base para las excepciones predefinidas que se generan para varios "
"errores aritméticos: :exc:`OverflowError`, :exc:`ZeroDivisionError`, :exc:"
"`FloatingPointError`."

#: ../Doc/library/exceptions.rst:118
msgid ""
"Raised when a :ref:`buffer <bufferobjects>` related operation cannot be "
"performed."
msgstr ""
"Se genera cuando :ref:`buffer <bufferobjects>` no se puede realizar una "
"operación relacionada."

#: ../Doc/library/exceptions.rst:124
msgid ""
"The base class for the exceptions that are raised when a key or index used "
"on a mapping or sequence is invalid: :exc:`IndexError`, :exc:`KeyError`.  "
"This can be raised directly by :func:`codecs.lookup`."
msgstr ""
"La clase base para las excepciones que se generan cuando una clave o índice "
"utilizado en un mapa o secuencia que no es válido: :exc:`IndexError`, :exc:"
"`KeyError`. Esto se puede generar directamente por :func:`codecs.lookup`."

#: ../Doc/library/exceptions.rst:130
msgid "Concrete exceptions"
msgstr "Excepciones específicas"

#: ../Doc/library/exceptions.rst:132
msgid "The following exceptions are the exceptions that are usually raised."
msgstr ""
"Las siguientes excepciones son las excepciones que normalmente se generan."

#: ../Doc/library/exceptions.rst:138
msgid "Raised when an :keyword:`assert` statement fails."
msgstr ""
"Se genera cuando se produce un error en una instrucción :keyword:`assert`."

#: ../Doc/library/exceptions.rst:143
msgid ""
"Raised when an attribute reference (see :ref:`attribute-references`) or "
"assignment fails.  (When an object does not support attribute references or "
"attribute assignments at all, :exc:`TypeError` is raised.)"
msgstr ""
"Se genera cuando se produce un error en una referencia de atributo (ver :ref:"
"`attribute-references`) o la asignación falla. (Cuando un objeto no admite "
"referencias de atributos o asignaciones de atributos en absoluto, se genera :"
"exc:`TypeError`.)"

#: ../Doc/library/exceptions.rst:150
msgid ""
"Raised when the :func:`input` function hits an end-of-file condition (EOF) "
"without reading any data. (N.B.: the :meth:`io.IOBase.read` and :meth:`io."
"IOBase.readline` methods return an empty string when they hit EOF.)"
msgstr ""
"Se genera cuando la función :func:`input` alcanza una condición de fin de "
"archivo (EOF) sin leer ningún dato. (Note que el :meth:`io. IOBase.read` y :"
"meth:`io.IOBase.readline` retornan una cadena vacía cuando llegan a EOF.)"

#: ../Doc/library/exceptions.rst:157
msgid "Not currently used."
msgstr "No se usa actualmente."

#: ../Doc/library/exceptions.rst:162
msgid ""
"Raised when a :term:`generator` or :term:`coroutine` is closed; see :meth:"
"`generator.close` and :meth:`coroutine.close`.  It directly inherits from :"
"exc:`BaseException` instead of :exc:`Exception` since it is technically not "
"an error."
msgstr ""
"Se genera cuando un :term:`generator` o :term:`coroutine` está cerrado; ver :"
"meth:`generator.close` y :meth:`coroutine.close`. Hereda directamente de :"
"exc:`BaseException` en lugar de :exc:`Exception` ya que técnicamente no es "
"un error."

#: ../Doc/library/exceptions.rst:170
msgid ""
"Raised when the :keyword:`import` statement has troubles trying to load a "
"module.  Also raised when the \"from list\" in ``from ... import`` has a "
"name that cannot be found."
msgstr ""
"Se genera cuando la instrucción :keyword:`import` tiene problemas al "
"intentar cargar un módulo. También se produce cuando la *from list* en "
"``from ... import`` tiene un nombre que no se puede encontrar."

#: ../Doc/library/exceptions.rst:174
msgid ""
"The :attr:`name` and :attr:`path` attributes can be set using keyword-only "
"arguments to the constructor. When set they represent the name of the module "
"that was attempted to be imported and the path to any file which triggered "
"the exception, respectively."
msgstr ""
"Los atributos :attr:`name` y :attr:`path` solo se pueden establecer "
"utilizando argumentos de palabra clave en el constructor. Cuando se "
"establece, representan el nombre del módulo que se intentó importar y la "
"ruta de acceso a cualquier archivo que desencadenó la excepción, "
"respectivamente."

#: ../Doc/library/exceptions.rst:179
msgid "Added the :attr:`name` and :attr:`path` attributes."
msgstr "Se han añadido los atributos :attr:`name` y :attr:`path`."

#: ../Doc/library/exceptions.rst:184
msgid ""
"A subclass of :exc:`ImportError` which is raised by :keyword:`import` when a "
"module could not be located.  It is also raised when ``None`` is found in :"
"data:`sys.modules`."
msgstr ""
"Una subclase de :exc:`ImportError` que se genera mediante :keyword:`import` "
"cuando no se pudo encontrar un módulo. También se genera cuando ``None`` se "
"encuentra en :data:`sys.modules`."

#: ../Doc/library/exceptions.rst:193
msgid ""
"Raised when a sequence subscript is out of range.  (Slice indices are "
"silently truncated to fall in the allowed range; if an index is not an "
"integer, :exc:`TypeError` is raised.)"
msgstr ""
"Se genera cuando un subíndice de secuencia está fuera del rango. (Los "
"índices de la rebanada son truncados silenciosamente para caer en el "
"intervalo permitido; si un índice no es un entero, se genera :exc:"
"`TypeError`.)"

#: ../Doc/library/exceptions.rst:202
msgid ""
"Raised when a mapping (dictionary) key is not found in the set of existing "
"keys."
msgstr ""
"Se genera cuando no se encuentra una clave de asignación (diccionario) en el "
"conjunto de claves existentes (mapa)."

#: ../Doc/library/exceptions.rst:209
msgid ""
"Raised when the user hits the interrupt key (normally :kbd:`Control-C` or :"
"kbd:`Delete`).  During execution, a check for interrupts is made regularly. "
"The exception inherits from :exc:`BaseException` so as to not be "
"accidentally caught by code that catches :exc:`Exception` and thus prevent "
"the interpreter from exiting."
msgstr ""
"Se genera cuando el usuario pulsa la tecla de interrupción (normalmente :kbd:"
"`Control-C` o :kbd:`Delete`). Durante la ejecución, se realiza una "
"comprobación de interrupciones con regularidad. La excepción hereda de :exc:"
"`BaseException` para no ser detectada de forma accidental por :exc:"
"`Exception` y, por lo tanto, prevenir que el intérprete salga."

#: ../Doc/library/exceptions.rst:218
msgid ""
"Raised when an operation runs out of memory but the situation may still be "
"rescued (by deleting some objects).  The associated value is a string "
"indicating what kind of (internal) operation ran out of memory. Note that "
"because of the underlying memory management architecture (C's :c:func:"
"`malloc` function), the interpreter may not always be able to completely "
"recover from this situation; it nevertheless raises an exception so that a "
"stack traceback can be printed, in case a run-away program was the cause."
msgstr ""
"Se genera cuando una operación se queda sin memoria pero la situación aún "
"puede ser recuperada (eliminando algunos objetos). El valor asociado es una "
"cadena que indica que tipo de operación (interna) se quedó sin memoria. "
"Tenga en cuenta que debido a la arquitectura de administración de memoria "
"(función :c:func:`malloc` de C), el intérprete no siempre puede recuperarse "
"completamente de esta situación; sin embargo, plantea una excepción para que "
"se pueda imprimir un seguimiento de la pila, en caso de que un programa "
"fuera de servicio fuera lo causa."

#: ../Doc/library/exceptions.rst:229
msgid ""
"Raised when a local or global name is not found.  This applies only to "
"unqualified names.  The associated value is an error message that includes "
"the name that could not be found."
msgstr ""
"Se genera cuando no se encuentra un nombre local o global. Esto se aplica "
"solo a nombres no calificados. El valor asociado es un mensaje de error que "
"incluye el nombre que no se pudo encontrar."

#: ../Doc/library/exceptions.rst:236
msgid ""
"This exception is derived from :exc:`RuntimeError`.  In user defined base "
"classes, abstract methods should raise this exception when they require "
"derived classes to override the method, or while the class is being "
"developed to indicate that the real implementation still needs to be added."
msgstr ""
"Esta excepción se deriva de :exc:`RuntimeError`. En las clases base "
"definidas por el usuario, los métodos abstractos deberían generar esta "
"excepción cuando requieren clases derivadas para anular el método, o "
"mientras se desarrolla la clase para indicar que la implementación real aún "
"necesita ser agregada."

#: ../Doc/library/exceptions.rst:243
msgid ""
"It should not be used to indicate that an operator or method is not meant to "
"be supported at all -- in that case either leave the operator / method "
"undefined or, if a subclass, set it to :data:`None`."
msgstr ""
"No debe usarse para indicar que un operador o método no debe ser admitido en "
"absoluto -- en ese caso, deje el operador / método sin definir o, si es una "
"subclase, se establece en :data:`None`."

#: ../Doc/library/exceptions.rst:249
msgid ""
"``NotImplementedError`` and ``NotImplemented`` are not interchangeable, even "
"though they have similar names and purposes.  See :data:`NotImplemented` for "
"details on when to use it."
msgstr ""
"``NotImplementedError`` y ``NotImplemented`` no son intercambiables, a pesar "
"de que tienen nombres y propósitos similares. Consulte :data:"
"`NotImplemented` para obtener detalles sobre cuándo usarlo."

#: ../Doc/library/exceptions.rst:258
msgid ""
"This exception is raised when a system function returns a system-related "
"error, including I/O failures such as \"file not found\" or \"disk full"
"\" (not for illegal argument types or other incidental errors)."
msgstr ""
"Esta excepción se produce cuando una función del sistema retorna un error "
"relacionado con el sistema, que incluye fallas de E/S como ``file not "
"found`` o ``disk full`` (no para tipos de argumentos ilegales u otros "
"errores incidentales)."

#: ../Doc/library/exceptions.rst:262
msgid ""
"The second form of the constructor sets the corresponding attributes, "
"described below.  The attributes default to :const:`None` if not specified.  "
"For backwards compatibility, if three arguments are passed, the :attr:"
"`~BaseException.args` attribute contains only a 2-tuple of the first two "
"constructor arguments."
msgstr ""
"La segunda forma del constructor establece los atributos correspondientes, "
"que se describen a continuación. Los atributos predeterminados son :const:"
"`None` si no se especificam. Para compatibilidad con versiones anteriores, "
"si se pasan tres argumentos, el atributo :attr:`~BaseException.args` "
"contiene solo una tupla de 2 de los dos primeros argumentos del constructor."

#: ../Doc/library/exceptions.rst:268
msgid ""
"The constructor often actually returns a subclass of :exc:`OSError`, as "
"described in `OS exceptions`_ below.  The particular subclass depends on the "
"final :attr:`.errno` value.  This behaviour only occurs when constructing :"
"exc:`OSError` directly or via an alias, and is not inherited when "
"subclassing."
msgstr ""
"El constructor a menudo retorna una subclase de :exc:`OSError`, como se "
"describe en `OS exceptions`_ a continuación. La subclase particular depende "
"del valor final :attr:`.errno`. Este comportamiento solo ocurre cuando se "
"construye :exc:`OSError` directamente o mediante un alias, y no se hereda al "
"derivar."

#: ../Doc/library/exceptions.rst:276
msgid "A numeric error code from the C variable :c:data:`errno`."
msgstr "Un código de error numérico de la variable C, :c:data:`errno`."

#: ../Doc/library/exceptions.rst:280
msgid ""
"Under Windows, this gives you the native Windows error code.  The :attr:`."
"errno` attribute is then an approximate translation, in POSIX terms, of that "
"native error code."
msgstr ""
"En Windows, esto le proporciona el código de error nativo de Windows. El "
"atributo :attr:`.errno` es entonces una traducción aproximada, en términos "
"POSIX, de ese código de error nativo."

#: ../Doc/library/exceptions.rst:284
msgid ""
"Under Windows, if the *winerror* constructor argument is an integer, the :"
"attr:`.errno` attribute is determined from the Windows error code, and the "
"*errno* argument is ignored.  On other platforms, the *winerror* argument is "
"ignored, and the :attr:`winerror` attribute does not exist."
msgstr ""
"En Windows, si el argumento del constructor ``winerror`` es un entero, el "
"atributo :attr:`.errno` se determina a partir del código de error de Windows "
"y el argumento ``errno`` se ignora. En otras plataformas, el argumento "
"``winerror`` se ignora y el atributo :attr:`winerror` no existe."

#: ../Doc/library/exceptions.rst:292
msgid ""
"The corresponding error message, as provided by the operating system.  It is "
"formatted by the C functions :c:func:`perror` under POSIX, and :c:func:"
"`FormatMessage` under Windows."
msgstr ""
"El mensaje de error correspondiente, tal como lo proporciona el sistema "
"operativo. Está formateado por las funciones de C, :c:func:`perror` en "
"POSIX, y :c:func:`FormatMessage` en Windows."

#: ../Doc/library/exceptions.rst:300
msgid ""
"For exceptions that involve a file system path (such as :func:`open` or :"
"func:`os.unlink`), :attr:`filename` is the file name passed to the function. "
"For functions that involve two file system paths (such as :func:`os."
"rename`), :attr:`filename2` corresponds to the second file name passed to "
"the function."
msgstr ""
"Para las excepciones que involucran una ruta del sistema de archivos (como :"
"func:`open` o :func:`os.unlink`), :attr:`filename` es el nombre del archivo "
"pasado a la función. Para las funciones que involucran dos rutas del sistema "
"de archivos (como :func:`os.rename`), :attr:`filename2` corresponde al "
"segundo nombre de archivo pasado a la función."

#: ../Doc/library/exceptions.rst:307
msgid ""
":exc:`EnvironmentError`, :exc:`IOError`, :exc:`WindowsError`, :exc:`socket."
"error`, :exc:`select.error` and :exc:`mmap.error` have been merged into :exc:"
"`OSError`, and the constructor may return a subclass."
msgstr ""
":exc:`EnvironmentError`, :exc:`IOError`, :exc:`WindowsError`, :exc:`socket."
"error`, :exc:`select.error` y :exc:`mmap.error` se han fusionado en :exc:"
"`OSError`, y el constructor puede retornar una subclase."

#: ../Doc/library/exceptions.rst:313
msgid ""
"The :attr:`filename` attribute is now the original file name passed to the "
"function, instead of the name encoded to or decoded from the filesystem "
"encoding.  Also, the *filename2* constructor argument and attribute was "
"added."
msgstr ""
"El atributo :attr:`filename` es ahora el nombre del archivo original pasado "
"a la función, en lugar del nombre codificado o descodificado de la "
"codificación del sistema de archivos. Además, se agregó el argumento "
"constructor ``filename2`` y el atributo."

#: ../Doc/library/exceptions.rst:322
msgid ""
"Raised when the result of an arithmetic operation is too large to be "
"represented.  This cannot occur for integers (which would rather raise :exc:"
"`MemoryError` than give up).  However, for historical reasons, OverflowError "
"is sometimes raised for integers that are outside a required range.   "
"Because of the lack of standardization of floating point exception handling "
"in C, most floating point operations are not checked."
msgstr ""
"Se genera cuando el resultado de una operación aritmética es demasiado "
"grande para ser representado. Esto no puede ocurrir para los enteros (para "
"lo cual es mejor elevar :exc:`MemoryError` que darse por vencido). Sin "
"embargo, por razones históricas, ``OverflowError`` a veces se genera para "
"enteros que están fuera del rango requerido. Debido a la falta de "
"estandarización del manejo de excepciones de coma flotante en C, la mayoría "
"de las operaciones de coma flotante no se verifican."

#: ../Doc/library/exceptions.rst:332
msgid ""
"This exception is derived from :exc:`RuntimeError`.  It is raised when the "
"interpreter detects that the maximum recursion depth (see :func:`sys."
"getrecursionlimit`) is exceeded."
msgstr ""
"Esta excepción se deriva de :exc:`RuntimeError`. Se eleva cuando el "
"intérprete detecta que se excede la profundidad máxima de recursión (ver :"
"func:`sys.getrecursionlimit`)."

#: ../Doc/library/exceptions.rst:336
msgid "Previously, a plain :exc:`RuntimeError` was raised."
msgstr "Anteriormente, se planteó un simple :exc:`RuntimeError`."

#: ../Doc/library/exceptions.rst:342
msgid ""
"This exception is raised when a weak reference proxy, created by the :func:"
"`weakref.proxy` function, is used to access an attribute of the referent "
"after it has been garbage collected. For more information on weak "
"references, see the :mod:`weakref` module."
msgstr ""
"Esta excepción se produce cuando un proxy de referencia débil, creado por la "
"función :func:`weakref.proxy`, se utiliza para acceder a un atributo del "
"referente después de que se ha recolectado basura. Para obtener más "
"información sobre referencias débiles, consulte el módulo :mod:`weakref` ."

#: ../Doc/library/exceptions.rst:350
msgid ""
"Raised when an error is detected that doesn't fall in any of the other "
"categories.  The associated value is a string indicating what precisely went "
"wrong."
msgstr ""
"Se genera cuando se detecta un error que no corresponde a ninguna de las "
"otras categorías. El valor asociado es una cadena que indica exactamente qué "
"salió mal."

#: ../Doc/library/exceptions.rst:357
msgid ""
"Raised by built-in function :func:`next` and an :term:`iterator`\\'s :meth:"
"`~iterator.__next__` method to signal that there are no further items "
"produced by the iterator."
msgstr ""
"Generado por la función incorporada :func:`next` y un :term:`iterator`\\'s :"
"meth:`~iterator.__next__` para indicar que no hay más elementos producidos "
"por el iterador."

#: ../Doc/library/exceptions.rst:361
msgid ""
"The exception object has a single attribute :attr:`value`, which is given as "
"an argument when constructing the exception, and defaults to :const:`None`."
msgstr ""
"El objeto de excepción tiene un solo atributo :attr:`value`, que se "
"proporciona como argumento al construir la excepción, y por defecto es :"
"const:`None`."

#: ../Doc/library/exceptions.rst:365
msgid ""
"When a :term:`generator` or :term:`coroutine` function returns, a new :exc:"
"`StopIteration` instance is raised, and the value returned by the function "
"is used as the :attr:`value` parameter to the constructor of the exception."
msgstr ""
"Cuando se retorna una función :term:`generator` o :term:`coroutine`, se "
"genera una nueva instancia :exc:`StopIteration`, y el valor retornado por la "
"función se utiliza como parámetro :attr:`value` para constructor de la "
"excepción."

#: ../Doc/library/exceptions.rst:370
msgid ""
"If a generator code directly or indirectly raises :exc:`StopIteration`, it "
"is converted into a :exc:`RuntimeError` (retaining the :exc:`StopIteration` "
"as the new exception's cause)."
msgstr ""
"Si un generador lanza directa o indirectamente :exc:`StopIteration`, se "
"convierte en :exc:`RuntimeError` (conservando :exc:`StopIteration` como la "
"causa de la nueva excepción)."

#: ../Doc/library/exceptions.rst:374
msgid ""
"Added ``value`` attribute and the ability for generator functions to use it "
"to return a value."
msgstr ""
"Se agregó el atributo `*value*` y la capacidad de las funciones del "
"generador de usarlo para retornar un valor."

#: ../Doc/library/exceptions.rst:378
msgid ""
"Introduced the RuntimeError transformation via ``from __future__ import "
"generator_stop``, see :pep:`479`."
msgstr ""
"Introdujo la transformación *RuntimeError* a través de ``from __future__ "
"import generator_stop``, ver :pep:`479`."

#: ../Doc/library/exceptions.rst:382
msgid ""
"Enable :pep:`479` for all code by default: a :exc:`StopIteration` error "
"raised in a generator is transformed into a :exc:`RuntimeError`."
msgstr ""
"Habilitar :pep:`479` para todo el código por defecto: a :exc:`StopIteration` "
"generado en un generador se transforma en :exc:`RuntimeError`."

#: ../Doc/library/exceptions.rst:388
msgid ""
"Must be raised by :meth:`__anext__` method of an :term:`asynchronous "
"iterator` object to stop the iteration."
msgstr ""
"Se debe generar mediante :meth:`__anext__` de un objeto :term:`asynchronous "
"iterator` para detener la iteración."

#: ../Doc/library/exceptions.rst:395
msgid ""
"Raised when the parser encounters a syntax error.  This may occur in an :"
"keyword:`import` statement, in a call to the built-in functions :func:`exec` "
"or :func:`eval`, or when reading the initial script or standard input (also "
"interactively)."
msgstr ""
"Se genera cuando el analizador (parser) encuentra un error de sintaxis. Esto "
"puede ocurrir en una declaración :keyword:`import`, en una llamada a las "
"funciones predefinidas :func:`exec` o :func:`eval`, o al leer el script "
"inicial o la entrada estándar (también de forma interactiva)."

#: ../Doc/library/exceptions.rst:400
msgid ""
"Instances of this class have attributes :attr:`filename`, :attr:`lineno`, :"
"attr:`offset` and :attr:`text` for easier access to the details.  :func:"
"`str` of the exception instance returns only the message."
msgstr ""
"Las instancias de esta clase tienen atributos :attr:`filename`, :attr:"
"`lineno`, :attr:`offset` y :attr:`text` para facilitar el acceso a los "
"detalles. :func:`str` de la instancia de excepción retorna solo el mensaje."

#: ../Doc/library/exceptions.rst:407
msgid ""
"Base class for syntax errors related to incorrect indentation.  This is a "
"subclass of :exc:`SyntaxError`."
msgstr ""
"Clase base para errores de sintaxis relacionados con sangría incorrecta. "
"Esta es una subclase de :exc:`SyntaxError`."

#: ../Doc/library/exceptions.rst:413
msgid ""
"Raised when indentation contains an inconsistent use of tabs and spaces. "
"This is a subclass of :exc:`IndentationError`."
msgstr ""
"Se genera cuando la sangría contiene un uso inconsistente de pestañas y "
"espacios. Esta es una subclase de :exc:`IndentationError`."

#: ../Doc/library/exceptions.rst:419
msgid ""
"Raised when the interpreter finds an internal error, but the situation does "
"not look so serious to cause it to abandon all hope. The associated value is "
"a string indicating what went wrong (in low-level terms)."
msgstr ""
"Se genera cuando el intérprete encuentra un error interno, pero la situación "
"no parece tan grave como para abandonar toda esperanza. El valor asociado es "
"una cadena que indica qué salió mal (a bajo nivel)."

#: ../Doc/library/exceptions.rst:423
msgid ""
"You should report this to the author or maintainer of your Python "
"interpreter. Be sure to report the version of the Python interpreter (``sys."
"version``; it is also printed at the start of an interactive Python "
"session), the exact error message (the exception's associated value) and if "
"possible the source of the program that triggered the error."
msgstr ""
"Debe informar esto al autor o responsable de su intérprete de Python. "
"Asegúrese de informar la versión del intérprete de Python (``sys.version``; "
"también se imprime al comienzo de una sesión interactiva de Python), el "
"mensaje de error exacto (el valor asociado de la excepción) y, si es "
"posible, la fuente del programa que activó el error."

#: ../Doc/library/exceptions.rst:432
msgid ""
"This exception is raised by the :func:`sys.exit` function.  It inherits "
"from :exc:`BaseException` instead of :exc:`Exception` so that it is not "
"accidentally caught by code that catches :exc:`Exception`.  This allows the "
"exception to properly propagate up and cause the interpreter to exit.  When "
"it is not handled, the Python interpreter exits; no stack traceback is "
"printed.  The constructor accepts the same optional argument passed to :func:"
"`sys.exit`. If the value is an integer, it specifies the system exit status "
"(passed to C's :c:func:`exit` function); if it is ``None``, the exit status "
"is zero; if it has another type (such as a string), the object's value is "
"printed and the exit status is one."
msgstr ""
"Esta excepción es provocada por la función :func:`sys.exit`. Hereda de :exc:"
"`BaseException` en lugar de :exc:`Exception` para que no sea gestionada "
"accidentalmente por el código que captura :exc:`Exception`. Esto permite que "
"la excepción se propague correctamente y que el intérprete salga. Cuando no "
"se maneja, el intérprete de Python sale; no se imprime el seguimiento de "
"pila. El constructor acepta el mismo argumento opcional pasado a :func:`sys."
"exit`. Si el valor es un entero, especifica el estado de salida del sistema "
"(se pasa a la función :c:func:`exit` de C); si es ``None``, el estado de "
"salida es cero; Si tiene otro tipo (como una cadena), se imprime el valor "
"del objeto y el estado de salida es uno."

#: ../Doc/library/exceptions.rst:443
msgid ""
"A call to :func:`sys.exit` is translated into an exception so that clean-up "
"handlers (:keyword:`finally` clauses of :keyword:`try` statements) can be "
"executed, and so that a debugger can execute a script without running the "
"risk of losing control.  The :func:`os._exit` function can be used if it is "
"absolutely positively necessary to exit immediately (for example, in the "
"child process after a call to :func:`os.fork`)."
msgstr ""
"Una llamada :func:`sys.exit` se traduce en una excepción para que los "
"gestores de limpieza (:keyword:`finally` cláusulas de :keyword:`try`) puedan "
"ejecutarse, y para que un depurador pueda ejecutar un *script* sin correr el "
"riesgo de perder el control. La función :func:`os._exit` se puede usar si es "
"absolutamente necesario salir (por ejemplo, en el proceso secundario después "
"de una llamada a :func:`os.fork`)."

#: ../Doc/library/exceptions.rst:452
msgid ""
"The exit status or error message that is passed to the constructor. "
"(Defaults to ``None``.)"
msgstr ""
"El estado de salida o mensaje de error que se pasa al constructor. (El valor "
"predeterminado es ``None``.)"

#: ../Doc/library/exceptions.rst:458
msgid ""
"Raised when an operation or function is applied to an object of "
"inappropriate type.  The associated value is a string giving details about "
"the type mismatch."
msgstr ""
"Se genera cuando una operación o función se aplica a un objeto de tipo "
"inapropiado. El valor asociado es una cadena que proporciona detalles sobre "
"la falta de coincidencia de tipos."

#: ../Doc/library/exceptions.rst:461
msgid ""
"This exception may be raised by user code to indicate that an attempted "
"operation on an object is not supported, and is not meant to be. If an "
"object is meant to support a given operation but has not yet provided an "
"implementation, :exc:`NotImplementedError` is the proper exception to raise."
msgstr ""
"El código de usuario puede generar esta excepción para indicar que un "
"intento de operación en un objeto no es compatible y no debe serlo. Si un "
"objeto está destinado a soportar una operación dada pero aún no ha "
"proporcionado una implementación, :exc:`NotImplementedError` es la excepción "
"adecuada para generar."

#: ../Doc/library/exceptions.rst:466
msgid ""
"Passing arguments of the wrong type (e.g. passing a :class:`list` when an :"
"class:`int` is expected) should result in a :exc:`TypeError`, but passing "
"arguments with the wrong value (e.g. a number outside expected boundaries) "
"should result in a :exc:`ValueError`."
msgstr ""
"Pasar argumentos del tipo incorrecto (por ejemplo, pasar a :class:`list` "
"cuando se espera un :class:`int`) debería dar como resultado :exc:"
"`TypeError`, pero pasar argumentos con el valor incorrecto (por ejemplo, un "
"número fuera límites esperados) debería dar como resultado :exc:`ValueError`."

#: ../Doc/library/exceptions.rst:473
msgid ""
"Raised when a reference is made to a local variable in a function or method, "
"but no value has been bound to that variable.  This is a subclass of :exc:"
"`NameError`."
msgstr ""
"Se genera cuando se hace referencia a una variable local en una función o "
"método, pero no se ha vinculado ningún valor a esa variable. Esta es una "
"subclase de :exc:`NameError`."

#: ../Doc/library/exceptions.rst:480
msgid ""
"Raised when a Unicode-related encoding or decoding error occurs.  It is a "
"subclass of :exc:`ValueError`."
msgstr ""
"Se genera cuando se produce un error de codificación o decodificación "
"relacionado con Unicode. Es una subclase de :exc:`ValueError`."

#: ../Doc/library/exceptions.rst:483
msgid ""
":exc:`UnicodeError` has attributes that describe the encoding or decoding "
"error.  For example, ``err.object[err.start:err.end]`` gives the particular "
"invalid input that the codec failed on."
msgstr ""
":exc:`UnicodeError` tiene atributos que describen el error de codificación o "
"decodificación. Por ejemplo, ``err.object[err.start:err.end]`` proporciona "
"la entrada inválida particular en la que falló el códec."

#: ../Doc/library/exceptions.rst:489
msgid "The name of the encoding that raised the error."
msgstr "El nombre de la codificación que provocó el error."

#: ../Doc/library/exceptions.rst:493
msgid "A string describing the specific codec error."
msgstr "Una cadena que describe el error de códec específico."

#: ../Doc/library/exceptions.rst:497
msgid "The object the codec was attempting to encode or decode."
msgstr "El objeto que el códec intentaba codificar o decodificar."

#: ../Doc/library/exceptions.rst:501
msgid "The first index of invalid data in :attr:`object`."
msgstr "El primer índice de datos no válidos en :attr:`object`."

#: ../Doc/library/exceptions.rst:505
msgid "The index after the last invalid data in :attr:`object`."
msgstr "El índice después de los últimos datos no válidos en :attr:`object`."

#: ../Doc/library/exceptions.rst:510
msgid ""
"Raised when a Unicode-related error occurs during encoding.  It is a "
"subclass of :exc:`UnicodeError`."
msgstr ""
"Se genera cuando se produce un error relacionado con Unicode durante la "
"codificación. Es una subclase de :exc:`UnicodeError`."

#: ../Doc/library/exceptions.rst:516
msgid ""
"Raised when a Unicode-related error occurs during decoding.  It is a "
"subclass of :exc:`UnicodeError`."
msgstr ""
"Se genera cuando se produce un error relacionado con Unicode durante la "
"codificación. Es una subclase de :exc:`UnicodeError`."

#: ../Doc/library/exceptions.rst:522
msgid ""
"Raised when a Unicode-related error occurs during translating.  It is a "
"subclass of :exc:`UnicodeError`."
msgstr ""
"Se genera cuando se produce un error relacionado con Unicode durante la "
"codificación. Es una subclase de :exc:`UnicodeError`."

#: ../Doc/library/exceptions.rst:528
msgid ""
"Raised when an operation or function receives an argument that has the right "
"type but an inappropriate value, and the situation is not described by a "
"more precise exception such as :exc:`IndexError`."
msgstr ""
"Se genera cuando una operación o función recibe un argumento que tiene el "
"tipo correcto pero un valor inapropiado, y la situación no se describe con "
"una excepción más precisa como :exc:`IndexError`."

#: ../Doc/library/exceptions.rst:535
msgid ""
"Raised when the second argument of a division or modulo operation is zero.  "
"The associated value is a string indicating the type of the operands and the "
"operation."
msgstr ""
"Se genera cuando el segundo argumento de una operación de división o módulo "
"es cero. El valor asociado es una cadena que indica el tipo de operandos y "
"la operación."

#: ../Doc/library/exceptions.rst:540
msgid ""
"The following exceptions are kept for compatibility with previous versions; "
"starting from Python 3.3, they are aliases of :exc:`OSError`."
msgstr ""
"Las siguientes excepciones se mantienen por compatibilidad con versiones "
"anteriores; a partir de Python 3.3, son alias de :exc:`OSError`."

#: ../Doc/library/exceptions.rst:549
msgid "Only available on Windows."
msgstr "Solo disponible en Windows."

#: ../Doc/library/exceptions.rst:553
msgid "OS exceptions"
msgstr "Excepciones del sistema operativo"

#: ../Doc/library/exceptions.rst:555
msgid ""
"The following exceptions are subclasses of :exc:`OSError`, they get raised "
"depending on the system error code."
msgstr ""
"Las siguientes excepciones son subclases de :exc:`OSError`, se generan según "
"el código de error del sistema."

#: ../Doc/library/exceptions.rst:560
msgid ""
"Raised when an operation would block on an object (e.g. socket) set for non-"
"blocking operation. Corresponds to :c:data:`errno` ``EAGAIN``, ``EALREADY``, "
"``EWOULDBLOCK`` and ``EINPROGRESS``."
msgstr ""
"Se genera cuando una operación se bloquearía en un objeto (por ejemplo, un "
"*socket*) configurado para una operación sin bloqueo. Corresponde a :c:data:"
"`errno` ``EAGAIN``, ``EALREADY``, ``EWOULDBLOCK`` y ``EINPROGRESS``."

#: ../Doc/library/exceptions.rst:565
msgid ""
"In addition to those of :exc:`OSError`, :exc:`BlockingIOError` can have one "
"more attribute:"
msgstr ""
"Además de los de :exc:`OSError`, :exc:`BlockingIOError` puede tener un "
"atributo más:"

#: ../Doc/library/exceptions.rst:570
msgid ""
"An integer containing the number of characters written to the stream before "
"it blocked.  This attribute is available when using the buffered I/O classes "
"from the :mod:`io` module."
msgstr ""
"Un entero que contiene el número de caracteres escritos en la secuencia "
"antes de que se bloquee. Este atributo está disponible cuando se utilizan "
"las clases de E/S almacenadas en el modulo :mod:`io`."

#: ../Doc/library/exceptions.rst:576
msgid ""
"Raised when an operation on a child process failed. Corresponds to :c:data:"
"`errno` ``ECHILD``."
msgstr ""
"Se genera cuando falla una operación en un proceso secundario. Corresponde :"
"c:data:`errno` ``ECHILD``."

#: ../Doc/library/exceptions.rst:581
msgid "A base class for connection-related issues."
msgstr "Una clase base para problemas relacionados con la conexión."

#: ../Doc/library/exceptions.rst:583
msgid ""
"Subclasses are :exc:`BrokenPipeError`, :exc:`ConnectionAbortedError`, :exc:"
"`ConnectionRefusedError` and :exc:`ConnectionResetError`."
msgstr ""
"Las subclases son :exc:`BrokenPipeError`, :exc:`ConnectionAbortedError`, :"
"exc:`ConnectionRefusedError` y :exc:`ConnectionResetError`."

#: ../Doc/library/exceptions.rst:588
msgid ""
"A subclass of :exc:`ConnectionError`, raised when trying to write on a pipe "
"while the other end has been closed, or trying to write on a socket which "
"has been shutdown for writing. Corresponds to :c:data:`errno` ``EPIPE`` and "
"``ESHUTDOWN``."
msgstr ""
"Una subclase de :exc:`ConnectionError`, que se genera cuando se intenta "
"escribir en una tubería mientras el otro extremo se ha cerrado, o cuando se "
"intenta escribir en un *socket* que se ha cerrado por escritura. Corresponde "
"a :c:data:`errno` ``EPIPE`` y ``ESHUTDOWN``."

#: ../Doc/library/exceptions.rst:595
msgid ""
"A subclass of :exc:`ConnectionError`, raised when a connection attempt is "
"aborted by the peer. Corresponds to :c:data:`errno` ``ECONNABORTED``."
msgstr ""
"Una subclase de :exc:`ConnectionError`, que se genera cuando el par "
"interrumpe un intento de conexión. Corresponde a :c:data:`errno` "
"``ECONNABORTED``."

#: ../Doc/library/exceptions.rst:601
msgid ""
"A subclass of :exc:`ConnectionError`, raised when a connection attempt is "
"refused by the peer. Corresponds to :c:data:`errno` ``ECONNREFUSED``."
msgstr ""
"Una subclase de :exc:`ConnectionError`, que se genera cuando el par "
"interrumpe un intento de conexión. Corresponde a :c:data:`errno` "
"``ECONNABORTED``."

#: ../Doc/library/exceptions.rst:607
msgid ""
"A subclass of :exc:`ConnectionError`, raised when a connection is reset by "
"the peer. Corresponds to :c:data:`errno` ``ECONNRESET``."
msgstr ""
"Una subclase de :exc:`ConnectionError`, que se genera cuando el par "
"restablece una conexión. Corresponde a :c:data:`errno` ``ECONNRESET``."

#: ../Doc/library/exceptions.rst:613
msgid ""
"Raised when trying to create a file or directory which already exists. "
"Corresponds to :c:data:`errno` ``EEXIST``."
msgstr ""
"Se genera al intentar crear un archivo o directorio que ya existe. "
"Corresponde a :c:data:`errno` ``EEXIST``."

#: ../Doc/library/exceptions.rst:618
msgid ""
"Raised when a file or directory is requested but doesn't exist. Corresponds "
"to :c:data:`errno` ``ENOENT``."
msgstr ""
"Se genera cuando se solicita un archivo o directorio pero no existe. "
"Corresponde a :c:data:`errno` ``ENOENT``."

#: ../Doc/library/exceptions.rst:623
msgid ""
"Raised when a system call is interrupted by an incoming signal. Corresponds "
"to :c:data:`errno` :py:data:`~errno.EINTR`."
msgstr ""
"Se genera cuando una llamada entrante interrumpe una llamada del sistema. "
"Corresponde a :c:data:`errno` :py:data:`~errno.EINTR`."

#: ../Doc/library/exceptions.rst:626
msgid ""
"Python now retries system calls when a syscall is interrupted by a signal, "
"except if the signal handler raises an exception (see :pep:`475` for the "
"rationale), instead of raising :exc:`InterruptedError`."
msgstr ""
"Python ahora vuelve a intentar las llamadas del sistema cuando una señal "
"interrumpe un *syscall*, excepto si el gestor señala generar una excepción "
"(ver :pep:`475` para la justificación), en lugar de lanzar :exc:"
"`InterruptedError`."

#: ../Doc/library/exceptions.rst:633
msgid ""
"Raised when a file operation (such as :func:`os.remove`) is requested on a "
"directory. Corresponds to :c:data:`errno` ``EISDIR``."
msgstr ""
"Se genera cuando se solicita una operación de archivo (como :func:`os."
"remove`) en un directorio. Corresponde a: :c:data:`errno` ``EISDIR``."

#: ../Doc/library/exceptions.rst:639
msgid ""
"Raised when a directory operation (such as :func:`os.listdir`) is requested "
"on something which is not a directory. Corresponds to :c:data:`errno` "
"``ENOTDIR``."
msgstr ""
"Se genera cuando se solicita una operación de directorio (como :func:`os."
"listdir`) en algo que no es un directorio. Corresponde a :c:data:`errno` "
"``ENOTDIR``."

#: ../Doc/library/exceptions.rst:645
msgid ""
"Raised when trying to run an operation without the adequate access rights - "
"for example filesystem permissions. Corresponds to :c:data:`errno` "
"``EACCES`` and ``EPERM``."
msgstr ""
"Se genera cuando se intenta ejecutar una operación sin los derechos de "
"acceso adecuados, por ejemplo, permisos del sistema de archivos. Corresponde "
"a :c:data:`errno` ``EACCES`` y ``EPERM``."

#: ../Doc/library/exceptions.rst:651
msgid ""
"Raised when a given process doesn't exist. Corresponds to :c:data:`errno` "
"``ESRCH``."
msgstr ""
"Generado cuando un proceso dado no existe. Corresponde a :c:data:`errno` "
"``ESRCH``."

#: ../Doc/library/exceptions.rst:656
msgid ""
"Raised when a system function timed out at the system level. Corresponds to :"
"c:data:`errno` ``ETIMEDOUT``."
msgstr ""
"Se genera cuando se agota el tiempo de espera de una función del sistema a "
"nivel del sistema. Corresponde a :c:data:`errno` ``ETIMEDOUT``."

#: ../Doc/library/exceptions.rst:659
msgid "All the above :exc:`OSError` subclasses were added."
msgstr "Por lo anterior se agregaron las subclases :exc:`OSError`."

#: ../Doc/library/exceptions.rst:665
msgid ":pep:`3151` - Reworking the OS and IO exception hierarchy"
msgstr ""
":pep:`3151` - Reelaborando el sistema operativo y la jerarquía de "
"excepciones E/S"

#: ../Doc/library/exceptions.rst:671
msgid "Warnings"
msgstr "Advertencias"

#: ../Doc/library/exceptions.rst:673
msgid ""
"The following exceptions are used as warning categories; see the :ref:"
"`warning-categories` documentation for more details."
msgstr ""
"Las siguientes excepciones se utilizan como categorías de advertencia; "
"consulte la documentación de :ref:`warning-categories` para obtener más "
"detalles."

#: ../Doc/library/exceptions.rst:678
msgid "Base class for warning categories."
msgstr "Clase base para categorías de advertencia."

#: ../Doc/library/exceptions.rst:683
msgid "Base class for warnings generated by user code."
msgstr "Clase base para advertencias generadas por código de usuario."

#: ../Doc/library/exceptions.rst:688
msgid ""
"Base class for warnings about deprecated features when those warnings are "
"intended for other Python developers."
msgstr ""
"Clase base para advertencias sobre características obsoletas cuando esas "
"advertencias están destinadas a otros desarrolladores de Python."

#: ../Doc/library/exceptions.rst:691
msgid ""
"Ignored by the default warning filters, except in the ``__main__`` module (:"
"pep:`565`). Enabling the :ref:`Python Development Mode <devmode>` shows this "
"warning."
msgstr ""

#: ../Doc/library/exceptions.rst:698
msgid ""
"Base class for warnings about features which are obsolete and expected to be "
"deprecated in the future, but are not deprecated at the moment."
msgstr ""
"Clase base para advertencias sobre características que están obsoletas y que "
"se espera que sean obsoletas en el futuro, pero que no lo son en este "
"momento."

#: ../Doc/library/exceptions.rst:702
msgid ""
"This class is rarely used as emitting a warning about a possible upcoming "
"deprecation is unusual, and :exc:`DeprecationWarning` is preferred for "
"already active deprecations."
msgstr ""
"Esta clase rara vez se usa para emitir una advertencia sobre una posible "
"desaprobación próxima es inusual, y :exc:`DeprecationWarning` se prefiere "
"para las desaprobaciones ya activas."

#: ../Doc/library/exceptions.rst:706 ../Doc/library/exceptions.rst:730
#: ../Doc/library/exceptions.rst:748
msgid ""
"Ignored by the default warning filters. Enabling the :ref:`Python "
"Development Mode <devmode>` shows this warning."
msgstr ""

#: ../Doc/library/exceptions.rst:712
msgid "Base class for warnings about dubious syntax."
msgstr "Clase base para advertencias sobre sintaxis dudosa."

#: ../Doc/library/exceptions.rst:717
msgid "Base class for warnings about dubious runtime behavior."
msgstr ""
"Clase base para advertencias sobre comportamiento dudoso en tiempo de "
"ejecución."

#: ../Doc/library/exceptions.rst:722
msgid ""
"Base class for warnings about deprecated features when those warnings are "
"intended for end users of applications that are written in Python."
msgstr ""
"Clase base para advertencias sobre características en desuso cuando esas "
"advertencias están destinadas a usuarios finales de aplicaciones escritas en "
"Python."

#: ../Doc/library/exceptions.rst:728
msgid "Base class for warnings about probable mistakes in module imports."
msgstr ""
"Clase base para advertencias sobre posibles errores en la importación de "
"módulos."

#: ../Doc/library/exceptions.rst:736
msgid "Base class for warnings related to Unicode."
msgstr "Clase base para advertencias relacionadas con Unicode."

#: ../Doc/library/exceptions.rst:741
msgid ""
"Base class for warnings related to :class:`bytes` and :class:`bytearray`."
msgstr ""
"Clase base para advertencias relacionadas con :class:`bytes` y :class:"
"`bytearray`."

#: ../Doc/library/exceptions.rst:746
#, fuzzy
msgid "Base class for warnings related to resource usage."
msgstr "Clase base para advertencias relacionadas con Unicode."

#: ../Doc/library/exceptions.rst:756
msgid "Exception hierarchy"
msgstr "Jerarquía de excepción"

#: ../Doc/library/exceptions.rst:758
msgid "The class hierarchy for built-in exceptions is:"
msgstr "La jerarquía de clases para las excepciones incorporadas es:"

#~ msgid ""
#~ "Base class for warnings related to resource usage. Ignored by the default "
#~ "warning filters."
#~ msgstr ""
#~ "Clase base para advertencias relacionadas con el uso de recursos. "
#~ "Ignorado por los filtros de advertencia predeterminados."
