# Copyright (C) 2001-2020, Python Software Foundation
# This file is distributed under the same license as the Python package.
# Maintained by the python-doc-es workteam.
# docs-es@python.org / https://mail.python.org/mailman3/lists/docs-es.python.org/
# Check https://github.com/python/python-docs-es/blob/3.8/TRANSLATORS to get the list of volunteers
#
msgid ""
msgstr ""
"Project-Id-Version: Python 3.8\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-05-06 11:59-0400\n"
"PO-Revision-Date: 2020-10-26 06:52-0400\n"
"Language-Team: python-doc-es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"Last-Translator: \n"
"Language: es\n"
"X-Generator: Poedit 2.4.1\n"

#: ../Doc/library/urllib.error.rst:2
msgid ":mod:`urllib.error` --- Exception classes raised by urllib.request"
msgstr ""
":mod:`urllib.error` --- Clases de excepción lanzadas por urllib.request"

#: ../Doc/library/urllib.error.rst:10
msgid "**Source code:** :source:`Lib/urllib/error.py`"
msgstr "**Código fuente:** :source:`Lib/urllib/error.py`"

#: ../Doc/library/urllib.error.rst:14
msgid ""
"The :mod:`urllib.error` module defines the exception classes for exceptions "
"raised by :mod:`urllib.request`.  The base exception class is :exc:"
"`URLError`."
msgstr ""
"El módulo :mod:`urllib.error` define las clases de excepción para las "
"excepciones lanzadas por :mod:`urllib.request`. La clase de excepción base "
"es :exc:`URLError`."

#: ../Doc/library/urllib.error.rst:17
msgid ""
"The following exceptions are raised by :mod:`urllib.error` as appropriate:"
msgstr ""
"Las siguientes excepciones son lanzadas por :mod:`urllib.error` según sea "
"apropiado:"

#: ../Doc/library/urllib.error.rst:21
msgid ""
"The handlers raise this exception (or derived exceptions) when they run into "
"a problem.  It is a subclass of :exc:`OSError`."
msgstr ""
"Los gestores lanzan esta excepción (o excepciones derivadas) cuando "
"encuentran un problema. Es una subclase de :exc:`OSError`."

#: ../Doc/library/urllib.error.rst:26
msgid ""
"The reason for this error.  It can be a message string or another exception "
"instance."
msgstr ""
"El motivo de este error. Puede ser una cadena de mensaje u otra instancia de "
"una excepción."

#: ../Doc/library/urllib.error.rst:29
msgid ""
":exc:`URLError` has been made a subclass of :exc:`OSError` instead of :exc:"
"`IOError`."
msgstr ""
"Se ha convertido a :exc:`URLError` en una subclase de :exc:`OSError` en "
"lugar de :exc:`IOError`."

#: ../Doc/library/urllib.error.rst:36
msgid ""
"Though being an exception (a subclass of :exc:`URLError`), an :exc:"
"`HTTPError` can also function as a non-exceptional file-like return value "
"(the same thing that :func:`~urllib.request.urlopen` returns).  This is "
"useful when handling exotic HTTP errors, such as requests for authentication."
msgstr ""
"A pesar de ser una excepción (una subclase de :exc:`URLError`), un :exc:"
"`HTTPError` también puede funcionar como un valor de retorno no excepcional "
"de tipo archivo (lo mismo que retorna :func:`~urllib.request.urlopen`). Esto "
"es útil para gestionar errores HTTP exóticos, como peticiones de "
"autentificación."

#: ../Doc/library/urllib.error.rst:44
msgid ""
"An HTTP status code as defined in :rfc:`2616`.  This numeric value "
"corresponds to a value found in the dictionary of codes as found in :attr:"
"`http.server.BaseHTTPRequestHandler.responses`."
msgstr ""
"Un código de estado HTTP como los definidos en :rfc:`2616`. Este valor "
"numérico se corresponde con un valor de un diccionario de códigos como el "
"que hay en :attr:`http.server.BaseHTTPRequestHandler.responses`."

#: ../Doc/library/urllib.error.rst:50
msgid "This is usually a string explaining the reason for this error."
msgstr ""
"Normalmente esto es una cadena de caracteres que explica el motivo de este "
"error."

#: ../Doc/library/urllib.error.rst:54
msgid ""
"The HTTP response headers for the HTTP request that caused the :exc:"
"`HTTPError`."
msgstr ""
"Las cabeceras de la respuesta HTTP de la petición HTTP que causó el :exc:"
"`HTTPError`."

#: ../Doc/library/urllib.error.rst:61
msgid ""
"This exception is raised when the :func:`~urllib.request.urlretrieve` "
"function detects that the amount of the downloaded data is less than the "
"expected amount (given by the *Content-Length* header).  The :attr:`content` "
"attribute stores the downloaded (and supposedly truncated) data."
msgstr ""
"Esta excepción se lanza cuando la función :func:`~urllib.request."
"urlretrieve` detecta que la cantidad de datos descargados es menor que la "
"esperada (dada por la cabecera *Content-Length*). El atributo :attr:"
"`content` almacena los datos descargados (y supuestamente truncados)."
